#!/usr/bin/env node
/**
 * Cross-platform setup for kalamdb-simple-typescript.
 *
 * Requires only Node.js and the kalam CLI in your PATH.
 * Usage: node setup.mjs [--url <url>] [--user <user>] [--password <pass>]
 * Env:   KALAMDB_URL  KALAMDB_USER  KALAMDB_PASSWORD
 *
 * The helper creates a 'demo-user' (password: demo123) for the Playwright
 * tests. The kalam dev path uses root / kalamdb123 by default.
 */

import { spawnSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function parseArgs() {
  const args = process.argv.slice(2);
  const opts = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--url') opts.url = args[++i];
    else if (args[i] === '--user') opts.user = args[++i];
    else if (args[i] === '--password') opts.password = args[++i];
    else if (args[i] === '--force') opts.force = true;
  }
  return opts;
}

const args = parseArgs();
const url = args.url ?? process.env.KALAMDB_URL ?? 'http://127.0.0.1:2900';
const user = args.user ?? process.env.KALAMDB_USER ?? 'admin';
const password = args.password ?? process.env.KALAMDB_PASSWORD ?? 'kalamdb123';
const sqlFile = resolve(__dirname, 'kalam/schema.sql');
const envFile = resolve(__dirname, '.env.local');

function runKalam(commandArgs, { allowFailure = false } = {}) {
  const result = spawnSync(
    'kalam',
    ['--url', url, '--user', user, '--password', password, '--no-spinner', ...commandArgs],
    { stdio: allowFailure ? 'pipe' : 'inherit', encoding: 'utf8' },
  );

  if (result.error) {
    console.error('[setup] failed to run kalam:', result.error.message);
    console.error('[setup] make sure the kalam CLI is installed and in your PATH');
    console.error('[setup]   https://kalamdb.io/docs/getting-started/install');
    process.exit(1);
  }

  if (!allowFailure && result.status !== 0) {
    console.error(`[setup] kalam exited with code ${result.status}`);
    process.exit(result.status ?? 1);
  }

  return result;
}

async function ensureServerSetup() {
  let status;
  try {
    status = await fetch(`${url}/v1/api/auth/status`);
  } catch {
    return;
  }

  if (!status.ok) {
    return;
  }

  const body = await status.json().catch(() => null);
  if (body?.needs_setup !== true) {
    return;
  }

  const setup = await fetch(`${url}/v1/api/auth/setup`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      user,
      password,
      root_password: process.env.KALAMDB_ROOT_PASSWORD ?? password,
      email: null,
    }),
  });

  if (!setup.ok) {
    console.error(`[setup] auth setup failed: ${setup.status} ${await setup.text()}`);
    process.exit(1);
  }
}

console.log(`[setup] importing ${sqlFile}`);
console.log(`[setup] server: ${url}  user: ${user}`);

await ensureServerSetup();

console.log('[setup] ensuring demo-user exists');
runKalam(["--command", "CREATE USER 'demo-user' WITH PASSWORD 'demo123' ROLE 'user'"], { allowFailure: true });
runKalam(['--file', sqlFile]);

if (existsSync(envFile) && !args.force) {
  console.log('[setup] .env.local already exists — skipping (use --force to overwrite)');
} else {
  writeFileSync(
    envFile,
    [
      '# KalamDB Connection (generated by setup.mjs)',
      `VITE_KALAMDB_URL=${url}`,
      'VITE_KALAMDB_USER=demo-user',
      'VITE_KALAMDB_PASSWORD=demo123',
    ].join('\n') + '\n',
  );
  console.log('[setup] wrote .env.local');
}

console.log('[setup] done');
console.log('[setup] next: npm run dev');
