[package]
name = "comparison_pocketbase"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "comparison_pocketbase"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
comparison_common = { workspace = true }
crossbeam-queue = { workspace = true }
lazy_static = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
