// Generated by kalam schema gen. Do not edit.
// contract_hash: 3dfa9ecbdb6008d1c71422ea9df522bbc57c542187222627df92db7255468934

export * from './schema.js';

export type KalamQueryClient = {
  query: (sql: string, params?: unknown[]) => Promise<{
    status?: string;
    error?: unknown;
    results?: Array<{
      rows?: unknown;
      named_rows?: Array<Record<string, unknown>>;
    }>;
  }>;
};

export function createKalam(_client?: KalamQueryClient) {
  return {
  };
}
