// Generated by kalam schema gen. Do not edit.
// contract_hash: 87991e0db242dad91799d6f4c993beed60fe5c04762054e5fe8da55cf3b2cddb

export * from './schema.js';

export type KalamQueryClient = {
  query: (sql: string, params?: unknown[]) => Promise<{
    status?: string;
    error?: unknown;
    results?: Array<{
      rows?: unknown;
      named_rows?: Array<Record<string, unknown>>;
    }>;
  }>;
};

export function createKalam(_client?: KalamQueryClient) {
  return {
  };
}
