// Generated by kalam schema gen. Do not edit.
// contract_hash: 3dfa9ecbdb6008d1c71422ea9df522bbc57c542187222627df92db7255468934

import type { FileRef } from '@kalamdb/client';
import { kTable, file, type KalamFileUpload } from '@kalamdb/orm';
import { sql } from 'drizzle-orm';
import { text, timestamp } from 'drizzle-orm/pg-core';

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
export type KalamFileColumn = FileRef | File | KalamFileUpload | Blob | null;

export type NestedStructBytes = Uint8Array;
export interface NestedCodec<T> {
  readonly typeId: string;
  encode(value: T): NestedStructBytes;
  decode(bytes: NestedStructBytes): T;
}

export type ContextFiles = {
  path: string;
  file_ref: KalamFileColumn;
  created_at: Date | null;
  updated_at: Date | null;
};


export const contextFiles = kTable.user("okf_sync.context_files", {
  path: text("path").primaryKey(),
  file_ref: file("file_ref").notNull(),
  created_at: timestamp("created_at", { mode: "date" }).default(sql``),
  updated_at: timestamp("updated_at", { mode: "date" }).default(sql``),
});

