// Generated by kalam schema gen. Do not edit.
// contract_hash: 87991e0db242dad91799d6f4c993beed60fe5c04762054e5fe8da55cf3b2cddb

import type { FileRef } from '@kalamdb/client';
import { kTable, file, type KalamFileUpload } from '@kalamdb/orm';
import { text, timestamp } from 'drizzle-orm/pg-core';

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
export type KalamFileColumn = FileRef | File | KalamFileUpload | Blob | null;

export type OkfSyncContextFiles = {
  path: string;
  file_ref: KalamFileColumn;
  created_at: Date | null;
  updated_at: Date | null;
};


export const okfSyncContextFiles = kTable.user("okf_sync.context_files", {
  path: text("path").primaryKey(),
  file_ref: file("file_ref").notNull(),
  created_at: timestamp("created_at", { mode: "date" }),
  updated_at: timestamp("updated_at", { mode: "date" }),
});

