#!/usr/bin/env node
/**
 * Cross-platform setup for kalamdb-chat-with-ai.
 *
 * Requires only Node.js and the kalam CLI in your PATH.
 * Usage: node setup.mjs [--url <url>] [--user <user>] [--password <pass>]
 * Env:   KALAMDB_URL  KALAMDB_USER  KALAMDB_PASSWORD
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function parseArgs() {
  const args = process.argv.slice(2);
  const opts = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--url') opts.url = args[++i];
    else if (args[i] === '--user') opts.user = args[++i];
    else if (args[i] === '--password') opts.password = args[++i];
    else if (args[i] === '--force') opts.force = true;
  }
  return opts;
}

const args = parseArgs();
const url = args.url ?? process.env.KALAMDB_URL ?? 'http://127.0.0.1:2900';
const user = args.user ?? process.env.KALAMDB_USER ?? 'admin';
const password = args.password ?? process.env.KALAMDB_PASSWORD ?? 'kalamdb123';
const sqlFile = resolve(__dirname, 'chat-app.sql');
const envFile = resolve(__dirname, '.env.local');
const seedMessagesSql = `EXECUTE AS USER 'admin' (INSERT INTO chat_demo.messages (role, author, sender_username, content) VALUES ('user', 'user_1', 'john_doe', 'Hello everyone!'), ('assistant', 'ai_bot', 'assistant', 'Hi John, how can I help?'))`;
const envFileContents = [
  '# KalamDB Connection (generated by setup.mjs)',
  `VITE_KALAMDB_URL=${url}`,
  `VITE_KALAMDB_USER=${user}`,
  `VITE_KALAMDB_PASSWORD=${password}`,
  '',
  `KALAMDB_URL=${url}`,
  `KALAMDB_USER=${user}`,
  `KALAMDB_PASSWORD=${password}`,
].join('\n') + '\n';

function runKalam(commandArgs, { allowFailure = false } = {}) {
  const result = spawnSync(
    'kalam',
    ['--url', url, '--user', user, '--password', password, '--no-spinner', ...commandArgs],
    { stdio: allowFailure ? 'pipe' : 'inherit', encoding: 'utf8' },
  );

  if (result.error) {
    console.error('[setup] failed to run kalam:', result.error.message);
    console.error('[setup] make sure the kalam CLI is installed and in your PATH');
    console.error('[setup]   https://kalamdb.io/docs/getting-started/install');
    process.exit(1);
  }

  if (!allowFailure && result.status !== 0) {
    console.error(`[setup] kalam exited with code ${result.status}`);
    process.exit(result.status ?? 1);
  }

  return result;
}

function formatKalamFailure(result) {
  return [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
}

function isProviderNotReady(result) {
  return /provider not found/i.test(formatKalamFailure(result));
}

async function seedInitialMessagesWithRetry() {
  for (let attempt = 1; attempt <= 6; attempt += 1) {
    const result = runKalam(['--command', seedMessagesSql], { allowFailure: true });
    if (result.status === 0) {
      return;
    }

    if (!isProviderNotReady(result) || attempt === 6) {
      const output = formatKalamFailure(result);
      if (output) {
        console.error(output);
      }
      console.error(`[setup] kalam exited with code ${result.status}`);
      process.exit(result.status ?? 1);
    }

    console.warn(`[setup] chat_demo.messages is not ready yet (seed attempt ${attempt}/6); retrying ...`);
    await new Promise((resolve) => setTimeout(resolve, attempt * 250));
  }
}

console.log(`[setup] importing ${sqlFile}`);
console.log(`[setup] server: ${url}  user: ${user}`);

console.log('[setup] resetting topic chat_demo.ai_inbox if it exists');
runKalam(['--command', 'DROP TOPIC chat_demo.ai_inbox'], { allowFailure: true });
runKalam(['--file', sqlFile]);
await seedInitialMessagesWithRetry();

if (existsSync(envFile) && !args.force) {
  const currentEnvFileContents = readFileSync(envFile, 'utf8');
  if (currentEnvFileContents === envFileContents) {
    console.log('[setup] .env.local already matches requested settings — skipping');
  } else {
    writeFileSync(envFile, envFileContents);
    console.log('[setup] refreshed .env.local to match requested settings');
  }
} else {
  writeFileSync(envFile, envFileContents);
  console.log('[setup] wrote .env.local');
}

console.log('[setup] done');
console.log('[setup] next: npm run agent  (in one terminal)');
console.log('[setup]       npm run dev    (in another)');
