import 'package:flutter_test/flutter_test.dart';

void main() {
  group('kalam CLI workflow Dart targets', () {
    const sampleKalamCliDart = '''
// Generated by kalam schema gen. Do not edit.
// Row codecs and KalamTableSpec values for kalam_sync.
// Action queues stay with kalam_sync_generator / build_runner.
import 'package:kalam_sync/kalam_sync.dart';

final class Users {
  const Users({
    required this.id,
    required this.email,
  });

  final int id;
  final String email;

  String get kalamRowKey => id.toString();

  Map<String, Object?> toJson() => {
        'id': id,
        'email': email,
      };

  factory Users.fromJson(Map<String, Object?> json) => Users(
        id: _asInt(json['id']),
        email: _asString(json['email']),
      );
}

abstract final class KalamTables {
  KalamTables._();

  static final users = KalamTableSpec<Users>(
    tableId: 'users',
    keyColumn: 'id',
    mode: KalamSyncMode.bidirectional,
    keyOf: (row) => row.kalamRowKey,
    encode: (row) => row.toJson(),
    decode: Users.fromJson,
  );
}
''';

    test('matches current schema gen contract', () {
      expect(sampleKalamCliDart, contains('Generated by kalam schema gen'));
      expect(sampleKalamCliDart, contains("import 'package:kalam_sync/kalam_sync.dart';"));
      expect(sampleKalamCliDart, contains('KalamTableSpec<Users>'));
      expect(sampleKalamCliDart, contains('mode: KalamSyncMode.bidirectional'));
      expect(sampleKalamCliDart.toLowerCase(), isNot(contains('placeholder')));
    });
  });
}
