import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

// Sample output shape produced by `kalam schema gen` for TypeScript targets.
const sampleKalamCliTypescript = `// Generated by @kalamdb/orm. Regenerate with the kalamdb-orm CLI after schema changes.
import { getKalamTableConfig, kSystemColumns, kTable } from '@kalamdb/orm';
import { integer, text } from 'drizzle-orm/pg-core';

export const app_users = kTable.user("app.users", {
  ...kSystemColumns(["_seq","_deleted"] as const),
  id: integer("id").primaryKey(),
  email: text("email").notNull(),
}, { systemColumns: true });
export const app_usersConfig = getKalamTableConfig(app_users)!;
export type AppUsers = typeof app_users.$inferSelect;
export type NewAppUsers = typeof app_users.$inferInsert;
`;

describe('kalam CLI workflow TypeScript targets', () => {
  it('matches orm-generated contract', () => {
    assert.match(sampleKalamCliTypescript, /Generated by @kalamdb\/orm/);
    assert.match(sampleKalamCliTypescript, /import \{ getKalamTableConfig, kSystemColumns, kTable \} from '@kalamdb\/orm';/);
    assert.match(sampleKalamCliTypescript, /export const app_users = kTable\.user\("app\.users"/);
    assert.match(sampleKalamCliTypescript, /export const app_usersConfig/);
    assert.match(sampleKalamCliTypescript, /export type AppUsers = typeof app_users\.\$inferSelect;/);
  });
});
