import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

// Sample output shape produced by `kalam schema gen` for TypeScript targets.
const sampleKalamCliTypescript = `// Generated by kalam schema gen. Do not edit.

export interface Users {
  id: number;
  email: string;
  created_at?: string;
}
`;

describe('kalam CLI workflow TypeScript targets', () => {
  it('matches generated interface contract', () => {
    assert.match(sampleKalamCliTypescript, /Generated by kalam schema gen/);
    assert.match(sampleKalamCliTypescript, /export interface Users/);
    assert.match(sampleKalamCliTypescript, /id: number;/);
    assert.match(sampleKalamCliTypescript, /email: string;/);
    assert.match(sampleKalamCliTypescript, /created_at\?: string;/);
  });
});
