import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

// Sample output shape produced by `kalam schema gen` for TypeScript targets.
const sampleKalamCliTypescript = `// Generated by @kalamdb/orm. Regenerate with the kalamdb-orm CLI after schema changes.
import { getKalamTableConfig, kTable } from '@kalamdb/orm';
import { integer, text } from 'drizzle-orm/pg-core';

export const users = kTable.user("users", {
  id: integer("id").primaryKey(),
  email: text("email").notNull(),
});
export const usersConfig = getKalamTableConfig(users)!;
export type Users = typeof users.$inferSelect;
export type NewUsers = typeof users.$inferInsert;
`;

describe('kalam CLI workflow TypeScript targets', () => {
  it('matches orm-generated contract', () => {
    assert.match(sampleKalamCliTypescript, /Generated by @kalamdb\/orm/);
    assert.match(sampleKalamCliTypescript, /import \{ getKalamTableConfig, kTable \} from '@kalamdb\/orm';/);
    assert.match(sampleKalamCliTypescript, /export const users = kTable\.user/);
    assert.match(sampleKalamCliTypescript, /export type Users = typeof users\.\$inferSelect;/);
  });
});
