// Generated by @kalamdb/orm. Regenerate with the kalamdb-orm CLI after schema changes.
import { file, getKalamTableConfig, kTable } from '@kalamdb/orm';
import { text, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const approval_actions = kTable.user("approval_actions", {
  id: text("id").default(sql``).primaryKey(),
  approval_id: text("approval_id").notNull(),
  conversation_id: text("conversation_id").notNull(),
  action: text("action").notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
});
export const approval_actionsConfig = getKalamTableConfig(approval_actions)!;
export type ApprovalActions = typeof approval_actions.$inferSelect;
export type NewApprovalActions = typeof approval_actions.$inferInsert;

export const approvals = kTable.user("approvals", {
  id: text("id").primaryKey(),
  conversation_id: text("conversation_id").notNull(),
  message_id: text("message_id").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  status: text("status").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``).notNull(),
});
export const approvalsConfig = getKalamTableConfig(approvals)!;
export type Approvals = typeof approvals.$inferSelect;
export type NewApprovals = typeof approvals.$inferInsert;

export const conversations = kTable.user("conversations", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  summary: text("summary").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``).notNull(),
});
export const conversationsConfig = getKalamTableConfig(conversations)!;
export type Conversations = typeof conversations.$inferSelect;
export type NewConversations = typeof conversations.$inferInsert;

export const messages = kTable.user("messages", {
  id: text("id").default(sql``).primaryKey(),
  client_id: text("client_id"),
  conversation_id: text("conversation_id").notNull(),
  reply_to_message_id: text("reply_to_message_id"),
  role: text("role").notNull(),
  body: text("body").notNull(),
  status: text("status").default(sql``).notNull(),
  attachment: file("attachment"),
  approval_id: text("approval_id"),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``).notNull(),
});
export const messagesConfig = getKalamTableConfig(messages)!;
export type Messages = typeof messages.$inferSelect;
export type NewMessages = typeof messages.$inferInsert;

export const typing_tokens = kTable.stream("typing_tokens", {
  id: text("id").default(sql``).primaryKey(),
  conversation_id: text("conversation_id").notNull(),
  message_id: text("message_id").notNull(),
  status: text("status").notNull(),
  token: text("token").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
});
export const typing_tokensConfig = getKalamTableConfig(typing_tokens)!;
export type TypingTokens = typeof typing_tokens.$inferSelect;
export type NewTypingTokens = typeof typing_tokens.$inferInsert;
