// Generated by @kalamdb/orm. Regenerate with the kalamdb-orm CLI after schema changes.
import { file, getKalamTableConfig, kSystemColumns, kTable } from '@kalamdb/orm';
import { text, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const react_ai_chat_approval_actions = kTable.user("react_ai_chat.approval_actions", {
  ...kSystemColumns(["_seq","_deleted"] as const),
  id: text("id").default(sql``).primaryKey(),
  approval_id: text("approval_id").notNull(),
  conversation_id: text("conversation_id").notNull(),
  action: text("action").notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const react_ai_chat_approval_actionsConfig = getKalamTableConfig(react_ai_chat_approval_actions)!;
export type ReactAiChatApprovalActions = typeof react_ai_chat_approval_actions.$inferSelect;
export type NewReactAiChatApprovalActions = typeof react_ai_chat_approval_actions.$inferInsert;

export const react_ai_chat_approvals = kTable.user("react_ai_chat.approvals", {
  ...kSystemColumns(["_seq","_deleted"] as const),
  id: text("id").primaryKey(),
  conversation_id: text("conversation_id").notNull(),
  message_id: text("message_id").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  status: text("status").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const react_ai_chat_approvalsConfig = getKalamTableConfig(react_ai_chat_approvals)!;
export type ReactAiChatApprovals = typeof react_ai_chat_approvals.$inferSelect;
export type NewReactAiChatApprovals = typeof react_ai_chat_approvals.$inferInsert;

export const react_ai_chat_conversations = kTable.user("react_ai_chat.conversations", {
  ...kSystemColumns(["_seq","_deleted"] as const),
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  summary: text("summary").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const react_ai_chat_conversationsConfig = getKalamTableConfig(react_ai_chat_conversations)!;
export type ReactAiChatConversations = typeof react_ai_chat_conversations.$inferSelect;
export type NewReactAiChatConversations = typeof react_ai_chat_conversations.$inferInsert;

export const react_ai_chat_messages = kTable.user("react_ai_chat.messages", {
  ...kSystemColumns(["_seq","_deleted"] as const),
  id: text("id").default(sql``).primaryKey(),
  client_id: text("client_id"),
  conversation_id: text("conversation_id").notNull(),
  reply_to_message_id: text("reply_to_message_id"),
  role: text("role").notNull(),
  body: text("body").notNull(),
  status: text("status").default(sql``).notNull(),
  attachment: file("attachment"),
  approval_id: text("approval_id"),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const react_ai_chat_messagesConfig = getKalamTableConfig(react_ai_chat_messages)!;
export type ReactAiChatMessages = typeof react_ai_chat_messages.$inferSelect;
export type NewReactAiChatMessages = typeof react_ai_chat_messages.$inferInsert;

export const react_ai_chat_typing_tokens = kTable.stream("react_ai_chat.typing_tokens", {
  ...kSystemColumns(["_seq"] as const),
  id: text("id").default(sql``).primaryKey(),
  conversation_id: text("conversation_id").notNull(),
  message_id: text("message_id").notNull(),
  status: text("status").notNull(),
  token: text("token").default(sql``).notNull(),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``).notNull(),
}, { systemColumns: true });
export const react_ai_chat_typing_tokensConfig = getKalamTableConfig(react_ai_chat_typing_tokens)!;
export type ReactAiChatTypingTokens = typeof react_ai_chat_typing_tokens.$inferSelect;
export type NewReactAiChatTypingTokens = typeof react_ai_chat_typing_tokens.$inferInsert;
