use crate::{
    error::Result,
    workflow::schema::{
        emitters::SchemaEmitter,
        model::{LanguageTarget, SchemaSnapshot, TableDefinition},
    },
};

pub struct DartEmitter;

impl SchemaEmitter for DartEmitter {
    fn language(&self) -> LanguageTarget {
        LanguageTarget::Dart
    }

    fn emit(&self, snapshot: &SchemaSnapshot) -> Result<String> {
        let mut out = String::from("// Generated by kalam schema gen. Do not edit.\n\n");

        for table in snapshot.tables.values() {
            out.push_str(&emit_table_class(table));
            out.push('\n');
        }

        Ok(out)
    }
}

fn emit_table_class(table: &TableDefinition) -> String {
    let class_name = to_pascal_case(&table.name);
    let mut lines = vec![format!("class {class_name} {{")];

    for column in &table.columns {
        let dart_type = map_sql_type(&column.sql_type, column.nullable);
        lines.push(format!("  final {} {};", dart_type, column.name));
    }

    lines.push(format!("\n  const {class_name}({{",));
    for column in &table.columns {
        lines.push(format!("    required this.{},", column.name));
    }
    lines.push("  });".to_string());
    lines.push("}".to_string());
    lines.join("\n")
}

fn map_sql_type(sql_type: &str, nullable: bool) -> String {
    let normalized = sql_type.trim().to_ascii_uppercase();
    let base = if normalized.contains("INT") {
        "int"
    } else if normalized.contains("BOOL") {
        "bool"
    } else if normalized.contains("TIMESTAMP") || normalized.contains("DATE") {
        "DateTime"
    } else {
        "String"
    };

    if nullable && base != "String" {
        format!("{base}?")
    } else {
        base.to_string()
    }
}

fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::workflow::schema::model::{ColumnDefinition, SchemaOrigin};
    use std::collections::BTreeMap;

    #[test]
    fn emits_class_from_table() {
        let mut tables = BTreeMap::new();
        tables.insert(
            "users".into(),
            TableDefinition {
                name: "users".into(),
                columns: vec![ColumnDefinition {
                    name: "id".into(),
                    sql_type: "INTEGER".into(),
                    nullable: false,
                    primary_key: true,
                }],
            },
        );
        let snapshot = SchemaSnapshot {
            origin: SchemaOrigin::File,
            tables,
            captured_at: chrono::Utc::now(),
        };

        let output = DartEmitter.emit(&snapshot).unwrap();
        assert!(output.contains("class Users"));
        assert!(output.contains("final int id;"));
    }
}
