use crate::{
    error::Result,
    workflow::schema::{
        emitters::SchemaEmitter,
        model::{LanguageTarget, SchemaSnapshot, TableDefinition},
    },
};

pub struct TypeScriptEmitter;

impl SchemaEmitter for TypeScriptEmitter {
    fn language(&self) -> LanguageTarget {
        LanguageTarget::TypeScript
    }

    fn emit(&self, snapshot: &SchemaSnapshot) -> Result<String> {
        let mut out = String::from("// Generated by kalam schema gen. Do not edit.\n\n");

        for table in snapshot.tables.values() {
            out.push_str(&emit_table_interface(table));
            out.push('\n');
        }

        Ok(out)
    }
}

fn emit_table_interface(table: &TableDefinition) -> String {
    let type_name = to_pascal_case(&table.name);
    let mut lines = vec![format!("export interface {type_name} {{")];

    for column in &table.columns {
        let ts_type = map_sql_type(&column.sql_type);
        let optional = if column.nullable { "?" } else { "" };
        lines.push(format!("  {}{}: {};", column.name, optional, ts_type));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

fn map_sql_type(sql_type: &str) -> &'static str {
    let normalized = sql_type.trim().to_ascii_uppercase();
    if normalized.contains("INT") {
        "number"
    } else if normalized.contains("BOOL") {
        "boolean"
    } else if normalized.contains("TIMESTAMP") || normalized.contains("DATE") {
        "string"
    } else {
        "string"
    }
}

fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::workflow::schema::model::{ColumnDefinition, SchemaOrigin};
    use std::collections::BTreeMap;

    #[test]
    fn emits_interface_from_table() {
        let mut tables = BTreeMap::new();
        tables.insert(
            "users".into(),
            TableDefinition {
                name: "users".into(),
                columns: vec![
                    ColumnDefinition {
                        name: "id".into(),
                        sql_type: "INTEGER".into(),
                        nullable: false,
                        primary_key: true,
                    },
                    ColumnDefinition {
                        name: "email".into(),
                        sql_type: "TEXT".into(),
                        nullable: true,
                        primary_key: false,
                    },
                ],
            },
        );
        let snapshot = SchemaSnapshot {
            origin: SchemaOrigin::File,
            tables,
            captured_at: chrono::Utc::now(),
        };

        let output = TypeScriptEmitter.emit(&snapshot).unwrap();
        assert!(output.contains("export interface Users"));
        assert!(output.contains("id: number;"));
        assert!(output.contains("email?: string;"));
    }
}
