// Generated by @kalamdb/orm. Regenerate with the kalamdb-orm CLI after schema changes.
import { file, getKalamTableConfig, kTable } from '@kalamdb/orm';
import { boolean, jsonb, text, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const context_files = kTable.user("context_files", {
  path: text("path").primaryKey(),
  file_ref: file("file_ref").notNull(),
  sha256: text("sha256").notNull(),
  base_sha256: text("base_sha256"),
  mime_type: text("mime_type").notNull(),
  size_bytes: text("size_bytes").notNull(),
  frontmatter: jsonb("frontmatter"),
  is_conflict: boolean("is_conflict").default(sql``),
  canonical_path: text("canonical_path"),
  deleted: boolean("deleted").default(sql``),
  created_at: timestamp("created_at", { mode: 'date' }).default(sql``),
  updated_at: timestamp("updated_at", { mode: 'date' }).default(sql``),
});
export const context_filesConfig = getKalamTableConfig(context_files)!;
export type ContextFiles = typeof context_files.$inferSelect;
export type NewContextFiles = typeof context_files.$inferInsert;
