// Generated by kalam schema gen. Do not edit.
// contract_hash: 307dbe0b1c57741744b56e085bbc922d91bf76998f675249543541a5b8889f5c

export * from './schema.js';

export type KalamQueryClient = {
  query: (sql: string, params?: unknown[]) => Promise<{
    status?: string;
    error?: unknown;
    results?: Array<{
      rows?: unknown;
      named_rows?: Array<Record<string, unknown>>;
    }>;
  }>;
};

export function createKalam(_client?: KalamQueryClient) {
  return {
  };
}
