// Generated by kalam schema gen. Do not edit.
// contract_hash: 19a25a1cf0b9b1aa8d21c1fa9cabb31b48f64c228279df6d9c6cc967f58e21bb

export * from './schema.js';

export type KalamQueryClient = {
  query: (sql: string, params?: unknown[]) => Promise<{
    status?: string;
    error?: unknown;
    results?: Array<{
      rows?: unknown;
      named_rows?: Array<Record<string, unknown>>;
    }>;
  }>;
};

export function createKalam(_client?: KalamQueryClient) {
  return {
  };
}
