// Generated by kalam schema gen. Do not edit.
// contract_hash: 307dbe0b1c57741744b56e085bbc922d91bf76998f675249543541a5b8889f5c

import { kTable } from '@kalamdb/orm';
import { sql } from 'drizzle-orm';
import { text, timestamp, bigint } from 'drizzle-orm/pg-core';

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type NestedStructBytes = Uint8Array;
export interface NestedCodec<T> {
  readonly typeId: string;
  encode(value: T): NestedStructBytes;
  decode(bytes: NestedStructBytes): T;
}

export type ActivityFeed = {
  id: bigint;
  service: string;
  level: string;
  actor: string;
  message: string;
  created_at: Date;
};


export const activityFeed = kTable.user("demo.activity_feed", {
  id: bigint("id", { mode: "bigint" }).default(sql``).primaryKey(),
  service: text("service").notNull(),
  level: text("level").notNull(),
  actor: text("actor").notNull(),
  message: text("message").notNull(),
  created_at: timestamp("created_at", { mode: "date" }).default(sql``).notNull(),
});

