// Generated by kalam schema gen. Do not edit.
// contract_hash: 19a25a1cf0b9b1aa8d21c1fa9cabb31b48f64c228279df6d9c6cc967f58e21bb

import { kTable } from '@kalamdb/orm';
import { text, timestamp, bigint } from 'drizzle-orm/pg-core';

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type DemoActivityFeed = {
  id: bigint;
  service: string;
  level: string;
  actor: string;
  message: string;
  created_at: Date;
};


export const demoActivityFeed = kTable.user("demo.activity_feed", {
  id: bigint("id", { mode: "bigint" }).primaryKey(),
  service: text("service").notNull(),
  level: text("level").notNull(),
  actor: text("actor").notNull(),
  message: text("message").notNull(),
  created_at: timestamp("created_at", { mode: "date" }).notNull(),
});

