// Build script to capture Git commit hash and build timestamp
// Sets environment variables for use in the binary at compile time
// Falls back to version.toml if git is not available (e.g., Docker builds)

use std::{env, ffi::OsStr, fs, path::Path, process::Command};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    generate_embedded_templates(&manifest_dir, &out_dir);
    // Try to read from version.toml first (for Docker/CI builds)
    let version_toml_path = "../version.toml";
    let fallback = read_version_toml(version_toml_path);

    // Capture Git commit hash (short version)
    let commit_hash = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok()
            } else {
                None
            }
        })
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| fallback.0.clone());

    // Capture build date/time in ISO 8601 format
    let build_date = chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC").to_string();

    // Capture Git branch name
    let branch = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok()
            } else {
                None
            }
        })
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| fallback.1.clone());

    // Set environment variables for use in the binary
    println!("cargo:rustc-env=GIT_COMMIT_HASH={}", commit_hash);
    println!("cargo:rustc-env=BUILD_DATE={}", build_date);
    println!("cargo:rustc-env=GIT_BRANCH={}", branch);

    // Re-run build script if .git/HEAD changes (new commits) or version.toml changes
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs/heads/");
    println!("cargo:rerun-if-changed=../version.toml");
    println!("cargo:rerun-if-changed=templates/");
}

fn generate_embedded_templates(manifest_dir: &str, out_dir: &str) {
    let templates_root = Path::new(manifest_dir).join("templates");
    let mut generated = String::from(
        "// @generated by build.rs — do not edit\n\n#[derive(Debug, Clone, Copy)]\npub struct \
         EmbeddedTemplateFile {\npub project_path: &'static str,\npub content: &'static \
         str,\n}\n\n#[derive(Debug, Clone, Copy)]\npub struct EmbeddedTemplate {\npub language: \
         &'static str,\npub id: &'static str,\npub description: &'static str,\npub version: \
         &'static str,\npub author: &'static str,\npub files: &'static \
         [EmbeddedTemplateFile],\n}\n\n",
    );

    let mut registry_entries = Vec::new();
    let mut symbol_index = 0usize;

    let languages = match fs::read_dir(&templates_root) {
        Ok(entries) => entries,
        Err(_) => {
            generated.push_str("pub const EMBEDDED_TEMPLATES: &[EmbeddedTemplate] = &[];\n");
            let output_path = Path::new(out_dir).join("embedded_templates.rs");
            fs::write(output_path, generated).expect("write embedded_templates.rs");
            return;
        },
    };

    for language_entry in languages.flatten() {
        let language_path = language_entry.path();
        if !language_path.is_dir() {
            continue;
        }
        let language = language_path
            .file_name()
            .and_then(OsStr::to_str)
            .unwrap_or_default()
            .to_string();

        let template_dirs = match fs::read_dir(&language_path) {
            Ok(entries) => entries,
            Err(_) => continue,
        };

        for template_entry in template_dirs.flatten() {
            let template_path = template_entry.path();
            if !template_path.is_dir() {
                continue;
            }
            let template_id = template_path
                .file_name()
                .and_then(OsStr::to_str)
                .unwrap_or_default()
                .to_string();

            let info_path = template_path.join("info.toml");
            let info = parse_info_toml(&info_path);
            let mut file_symbols = Vec::new();

            collect_template_files(
                manifest_dir,
                &language,
                &template_id,
                &template_path,
                &template_path,
                &mut symbol_index,
                &mut generated,
                &mut file_symbols,
            );

            if file_symbols.is_empty() {
                continue;
            }

            let files_const = format!(
                "TEMPLATE_{}_{}_FILES",
                sanitize_ident(&language).to_ascii_uppercase(),
                sanitize_ident(&template_id).to_ascii_uppercase()
            );
            generated.push_str(&format!(
                "const {files_const}: &[EmbeddedTemplateFile] = &[\n{}\n];\n\n",
                file_symbols.join("\n")
            ));
            registry_entries.push(format!(
                "EmbeddedTemplate {{\nlanguage: {language:?},\nid: {template_id:?},\ndescription: \
                 {description:?},\nversion: {version:?},\nauthor: {author:?},\nfiles: \
                 {files_const},\n}}",
                description = info.description,
                version = info.version,
                author = info.author,
            ));
        }
    }

    generated.push_str("pub const EMBEDDED_TEMPLATES: &[EmbeddedTemplate] = &[\n");
    for entry in &registry_entries {
        generated.push_str(entry);
        generated.push_str(",\n");
    }
    generated.push_str("];\n");

    let output_path = Path::new(out_dir).join("embedded_templates.rs");
    fs::write(output_path, generated).expect("write embedded_templates.rs");
}

struct TemplateInfo {
    description: String,
    version:     String,
    author:      String,
}

fn parse_info_toml(path: &Path) -> TemplateInfo {
    let mut info = TemplateInfo {
        description: String::new(),
        version:     String::new(),
        author:      String::new(),
    };

    let content = match fs::read_to_string(path) {
        Ok(content) => content,
        Err(_) => return info,
    };

    for line in content.lines() {
        let line = line.trim();
        if let Some(value) = extract_toml_field(line, "description") {
            info.description = value;
        } else if let Some(value) = extract_toml_field(line, "version") {
            info.version = value;
        } else if let Some(value) = extract_toml_field(line, "author") {
            info.author = value;
        }
    }

    info
}

fn collect_template_files(
    manifest_dir: &str,
    language: &str,
    template_id: &str,
    template_root: &Path,
    current_dir: &Path,
    symbol_index: &mut usize,
    generated: &mut String,
    file_symbols: &mut Vec<String>,
) {
    let entries = match fs::read_dir(current_dir) {
        Ok(entries) => entries,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_template_files(
                manifest_dir,
                language,
                template_id,
                template_root,
                &path,
                symbol_index,
                generated,
                file_symbols,
            );
            continue;
        }

        let file_name = path.file_name().and_then(OsStr::to_str).unwrap_or_default();
        if file_name == "info.toml" {
            continue;
        }

        let relative = path
            .strip_prefix(template_root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        let project_path = template_destination_path(&relative);
        let absolute = Path::new(manifest_dir)
            .join("templates")
            .join(language)
            .join(template_id)
            .join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));

        let symbol = format!("EMBEDDED_TEMPLATE_FILE_{symbol_index}");
        *symbol_index += 1;
        generated.push_str(&format!(
            "const {symbol}: &str = include_str!(r\"{absolute}\");\n",
            absolute = absolute.display()
        ));
        file_symbols.push(format!(
            "EmbeddedTemplateFile {{ project_path: {project_path:?}, content: {symbol} }},",
            project_path = project_path
        ));
    }
}

fn sanitize_ident(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn template_destination_path(relative_template_path: &str) -> String {
    if let Some(stripped) = relative_template_path.strip_suffix(".template") {
        stripped.replace('\\', "/")
    } else {
        relative_template_path.replace('\\', "/")
    }
}

/// Read fallback values from version.toml
/// Returns (commit_hash, branch, build_date) with defaults if file doesn't exist
fn read_version_toml(path: &str) -> (String, String, String) {
    let default = ("unknown".to_string(), "unknown".to_string(), "unknown".to_string());

    let content = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return default,
    };

    let mut commit = "unknown".to_string();
    let mut branch = "unknown".to_string();
    let mut build_date = "unknown".to_string();

    for line in content.lines() {
        let line = line.trim();
        if line.starts_with("git_commit_hash") {
            if let Some(val) = extract_toml_value(line) {
                commit = val;
            }
        } else if line.starts_with("git_branch") {
            if let Some(val) = extract_toml_value(line) {
                branch = val;
            }
        } else if line.starts_with("build_date") {
            if let Some(val) = extract_toml_value(line) {
                build_date = val;
            }
        }
    }

    (commit, branch, build_date)
}

/// Extract value from a TOML line like: key = "value"
fn extract_toml_value(line: &str) -> Option<String> {
    let key = line.split('=').next()?.trim();
    extract_toml_field(line, key).filter(|value| !value.is_empty() && value != "unknown")
}

fn extract_toml_field(line: &str, key: &str) -> Option<String> {
    let prefix = format!("{key} =");
    if !line.starts_with(&prefix) {
        return None;
    }
    let val = line[prefix.len()..].trim().trim_matches('"');
    if val.is_empty() {
        None
    } else {
        Some(val.to_string())
    }
}
