// Generated by kalam schema gen. Do not edit.
// contract_hash: 01f4a8ae0dfe3619edf4091a4e13b213f3cba67eb0b35b1dfd156c821564a46f

import { kTable } from '@kalamdb/orm';
import { text, timestamp, bigint } from 'drizzle-orm/pg-core';

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type BlogBlogs = {
  blog_id: bigint;
  content: string;
  summary: string | null;
  created: Date;
  updated: Date;
};

export type BlogSummaryFailures = {
  run_key: string;
  blog_id: string;
  error: string;
  created: Date;
  updated: Date;
};

export type BlogSummarizer =
  | ({ _table: "blog:blogs" } & BlogBlogs);

export const blogBlogs = kTable.shared("blog.blogs", {
  blog_id: bigint("blog_id", { mode: "bigint" }).primaryKey(),
  content: text("content").notNull(),
  summary: text("summary"),
  created: timestamp("created", { mode: "date" }).notNull(),
  updated: timestamp("updated", { mode: "date" }).notNull(),
});

export const blogSummaryFailures = kTable.shared("blog.summary_failures", {
  run_key: text("run_key").primaryKey(),
  blog_id: text("blog_id").notNull(),
  error: text("error").notNull(),
  created: timestamp("created", { mode: "date" }).notNull(),
  updated: timestamp("updated", { mode: "date" }).notNull(),
});

