// Generated by kalam schema gen. Do not edit.
// contract_hash: 01f4a8ae0dfe3619edf4091a4e13b213f3cba67eb0b35b1dfd156c821564a46f

export * from './schema.js';

export type KalamQueryClient = {
  query: (sql: string, params?: unknown[]) => Promise<{
    status?: string;
    error?: unknown;
    results?: Array<{
      rows?: unknown;
      named_rows?: Array<Record<string, unknown>>;
    }>;
  }>;
};

export function createKalam(_client?: KalamQueryClient) {
  return {
  };
}
