// Generated by kalam schema gen. Do not edit.
// contract_hash: 94b914a7c3faea66b759467f66a1b66466b6ce13578abcd09f6b61f8e9bd4e80

import { kTable } from '@kalamdb/orm';
import { sql } from 'drizzle-orm';
import { text, timestamp, bigint } from 'drizzle-orm/pg-core';

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type NestedStructBytes = Uint8Array;
export interface NestedCodec<T> {
  readonly typeId: string;
  encode(value: T): NestedStructBytes;
  decode(bytes: NestedStructBytes): T;
}

export type Blogs = {
  blog_id: bigint;
  content: string;
  summary: string | null;
  created: Date;
  updated: Date;
};

export type SummaryFailures = {
  run_key: string;
  blog_id: string;
  error: string;
  created: Date;
  updated: Date;
};

export type Summarizer =
  | ({ _table: "blog:blogs" } & Blogs);

export const blogs = kTable.shared("blog.blogs", {
  blog_id: bigint("blog_id", { mode: "bigint" }).default(sql``).primaryKey(),
  content: text("content").notNull(),
  summary: text("summary"),
  created: timestamp("created", { mode: "date" }).default(sql``).notNull(),
  updated: timestamp("updated", { mode: "date" }).default(sql``).notNull(),
});

export const summaryFailures = kTable.shared("blog.summary_failures", {
  run_key: text("run_key").primaryKey(),
  blog_id: text("blog_id").notNull(),
  error: text("error").notNull(),
  created: timestamp("created", { mode: "date" }).default(sql``).notNull(),
  updated: timestamp("updated", { mode: "date" }).default(sql``).notNull(),
});

