// Generated by kalam schema gen. Do not edit.
// contract_hash: 94b914a7c3faea66b759467f66a1b66466b6ce13578abcd09f6b61f8e9bd4e80

export * from './schema.js';

export type KalamQueryClient = {
  query: (sql: string, params?: unknown[]) => Promise<{
    status?: string;
    error?: unknown;
    results?: Array<{
      rows?: unknown;
      named_rows?: Array<Record<string, unknown>>;
    }>;
  }>;
};

export function createKalam(_client?: KalamQueryClient) {
  return {
  };
}
