//! Dart/Flutter schema generation from the language-neutral SQL snapshot.

use std::{
    collections::HashSet,
    fmt::Write,
    path::Path,
};

use crate::{
    error::{CLIError, Result},
    workflow::schema::model::{ColumnDefinition, SchemaSnapshot, TableDefinition, TableKind},
};

const GENERATED_HEADER: &str = "// Generated by kalam schema gen. Do not edit.\n\
// Row codecs and KalamTableSpec values for kalam_sync.\n\
// Action queues stay with kalam_sync_generator / build_runner.\n";

pub fn write_dart_schema(output_path: &Path, snapshot: &SchemaSnapshot) -> Result<()> {
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| {
            CLIError::FileError(format!("failed to create '{}': {error}", parent.display()))
        })?;
    }
    let source = generate_dart_source(snapshot);
    std::fs::write(output_path, source).map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", output_path.display()))
    })?;
    Ok(())
}

pub fn generate_dart_source(snapshot: &SchemaSnapshot) -> String {
    let tables: Vec<&TableDefinition> = snapshot.tables.values().collect();
    let mut used_class_names = HashSet::new();
    let mut used_const_names = HashSet::new();
    let generated: Vec<GeneratedTable> = tables
        .iter()
        .map(|table| GeneratedTable::from_definition(table, &mut used_class_names, &mut used_const_names))
        .collect();

    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("import 'package:kalam_sync/kalam_sync.dart';\n\n");

    if generated.is_empty() {
        out.push_str("abstract final class KalamTables {\n  KalamTables._();\n}\n");
        return out;
    }

    for table in &generated {
        table.write_row_class(&mut out);
        out.push('\n');
    }

    out.push_str("abstract final class KalamTables {\n  KalamTables._();\n\n");
    for table in &generated {
        table.write_spec(&mut out);
        out.push('\n');
    }
    out.push_str("}\n\n");
    out.push_str(DART_HELPERS);
    out
}

struct GeneratedTable {
    table_id: String,
    class_name: String,
    const_name: String,
    key_column: String,
    mode: &'static str,
    columns: Vec<GeneratedColumn>,
}

struct GeneratedColumn {
    sql_name: String,
    field_name: String,
    dart_type: &'static str,
    nullable: bool,
    is_key: bool,
}

impl GeneratedTable {
    fn from_definition(
        table: &TableDefinition,
        used_class_names: &mut HashSet<String>,
        used_const_names: &mut HashSet<String>,
    ) -> Self {
        let last_segment = table_name_segment(&table.name);
        let class_name = unique_ident(pascal_case(last_segment), used_class_names);
        let const_name = unique_ident(camel_case(last_segment), used_const_names);
        let key_column = key_column_name(&table.columns);
        let columns = table
            .columns
            .iter()
            .map(|column| {
                let nullable = column.nullable && !column.primary_key;
                GeneratedColumn {
                    sql_name: column.name.clone(),
                    field_name: dart_field_name(&column.name),
                    dart_type: dart_type_for_sql(&column.sql_type),
                    nullable,
                    is_key: key_column.as_deref() == Some(column.name.as_str()),
                }
            })
            .collect();

        Self {
            table_id: table.name.clone(),
            class_name,
            const_name,
            key_column: key_column.unwrap_or_else(|| "id".to_string()),
            mode: sync_mode(table.kind),
            columns,
        }
    }

    fn write_row_class(&self, out: &mut String) {
        let _ = writeln!(out, "final class {} {{", self.class_name);
        out.push_str("  const ");
        out.push_str(&self.class_name);
        out.push_str("({\n");
        for column in &self.columns {
            if column.nullable {
                let _ = writeln!(out, "    this.{},", column.field_name);
            } else {
                let _ = writeln!(out, "    required this.{},", column.field_name);
            }
        }
        out.push_str("  });\n\n");

        for column in &self.columns {
            let type_name = if column.nullable {
                format!("{}?", column.dart_type)
            } else {
                column.dart_type.to_string()
            };
            let _ = writeln!(out, "  final {type_name} {};", column.field_name);
        }

        out.push_str("\n  String get kalamRowKey => ");
        let key_expr = self
            .columns
            .iter()
            .find(|column| column.is_key)
            .or_else(|| self.columns.first());
        match key_expr {
            Some(key) if key.dart_type == "String" && !key.nullable => {
                out.push_str(&key.field_name);
            },
            Some(key) => {
                let _ = write!(out, "{}.toString()", key.field_name);
            },
            None => out.push_str("''"),
        }
        out.push_str(";\n\n");

        out.push_str("  Map<String, Object?> toJson() => {\n");
        for column in &self.columns {
            let encoded = encode_expression(column);
            let _ = writeln!(out, "        '{}': {encoded},", column.sql_name);
        }
        out.push_str("      };\n\n");

        let _ = writeln!(out, "  factory {}.fromJson(Map<String, Object?> json) => {}(", self.class_name, self.class_name);
        for column in &self.columns {
            let decoded = decode_expression(column);
            let _ = writeln!(out, "        {}: {decoded},", column.field_name);
        }
        out.push_str("      );\n}\n");
    }

    fn write_spec(&self, out: &mut String) {
        let _ = writeln!(
            out,
            "  static final {const_name} = KalamTableSpec<{class_name}>(",
            const_name = self.const_name,
            class_name = self.class_name
        );
        let _ = writeln!(out, "    tableId: '{}',", escape_dart_string(&self.table_id));
        let _ = writeln!(out, "    keyColumn: '{}',", escape_dart_string(&self.key_column));
        let _ = writeln!(out, "    mode: KalamSyncMode.{},", self.mode);
        out.push_str("    keyOf: (row) => row.kalamRowKey,\n");
        out.push_str("    encode: (row) => row.toJson(),\n");
        let _ = writeln!(out, "    decode: {}.fromJson,", self.class_name);
        out.push_str("  );\n");
    }
}

fn table_name_segment(name: &str) -> &str {
    name.rsplit('.').next().filter(|part| !part.is_empty()).unwrap_or(name)
}

fn key_column_name(columns: &[ColumnDefinition]) -> Option<String> {
    columns
        .iter()
        .find(|column| column.primary_key)
        .or_else(|| columns.iter().find(|column| column.name.eq_ignore_ascii_case("id")))
        .map(|column| column.name.clone())
}

fn sync_mode(kind: TableKind) -> &'static str {
    match kind {
        TableKind::Stream => "replicaOnly",
        TableKind::Unspecified | TableKind::User | TableKind::Shared => "bidirectional",
    }
}

fn dart_type_for_sql(sql_type: &str) -> &'static str {
    let normalized = sql_type.trim().trim_end_matches(',').to_ascii_uppercase();
    let base = normalized.split('(').next().unwrap_or(&normalized);
    match base {
        "INT" | "INTEGER" | "SMALLINT" | "BIGINT" | "INT2" | "INT4" | "INT8" | "INT64"
        | "UINT64" | "SERIAL" | "BIGSERIAL" => "int",
        "FLOAT" | "FLOAT4" | "FLOAT8" | "DOUBLE" | "REAL" | "NUMERIC" | "DECIMAL" => "double",
        "BOOLEAN" | "BOOL" => "bool",
        "TIMESTAMP" | "TIMESTAMPTZ" | "DATETIME" | "DATE" | "TIME" => "DateTime",
        "JSON" | "JSONB" | "FILE" => "Map<String, Object?>",
        "BYTES" | "BYTEA" | "BLOB" | "BINARY" => "String",
        "EMBEDDING" => "List<double>",
        _ => "String",
    }
}

fn dart_field_name(sql_name: &str) -> String {
    sanitize_ident(&camel_case(sql_name))
}

fn pascal_case(value: &str) -> String {
    let mut name = String::new();
    let mut capitalize = true;
    for ch in value.chars() {
        if ch == '_' || ch == '-' || ch == '.' {
            capitalize = true;
            continue;
        }
        if capitalize {
            for upper in ch.to_uppercase() {
                name.push(upper);
            }
            capitalize = false;
        } else {
            name.push(ch);
        }
    }
    sanitize_ident(&name)
}

fn camel_case(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => "value".to_string(),
    }
}

fn sanitize_ident(value: &str) -> String {
    let mut ident: String = value
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() || ch == '_' { ch } else { '_' })
        .collect();
    if ident.is_empty() || ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, 'n');
    }
    if DART_KEYWORDS.contains(&ident.as_str()) {
        ident.push('_');
    }
    ident
}

fn unique_ident(base: String, used: &mut HashSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }
    let mut index = 2u32;
    loop {
        let candidate = format!("{base}{index}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        index += 1;
    }
}

fn encode_expression(column: &GeneratedColumn) -> String {
    let name = &column.field_name;
    match (column.dart_type, column.nullable) {
        ("DateTime", true) => format!("{name}?.toIso8601String()"),
        ("DateTime", false) => format!("{name}.toIso8601String()"),
        _ => name.to_string(),
    }
}

fn decode_expression(column: &GeneratedColumn) -> String {
    let json = format!("json['{}']", escape_dart_string(&column.sql_name));
    match (column.dart_type, column.nullable) {
        ("int", false) => format!("_asInt({json})"),
        ("int", true) => format!("_asIntOrNull({json})"),
        ("double", false) => format!("_asDouble({json})"),
        ("double", true) => format!("_asDoubleOrNull({json})"),
        ("bool", false) => format!("_asBool({json})"),
        ("bool", true) => format!("_asBoolOrNull({json})"),
        ("DateTime", false) => format!("_asDateTime({json})"),
        ("DateTime", true) => format!("_asDateTimeOrNull({json})"),
        ("Map<String, Object?>", false) => format!("_asJsonMap({json})"),
        ("Map<String, Object?>", true) => format!("_asJsonMapOrNull({json})"),
        ("List<double>", false) => format!("_asDoubleList({json})"),
        ("List<double>", true) => format!("_asDoubleListOrNull({json})"),
        (_, false) => format!("_asString({json})"),
        (_, true) => format!("_asStringOrNull({json})"),
    }
}

fn escape_dart_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

const DART_KEYWORDS: &[&str] = &[
    "assert", "break", "case", "catch", "class", "const", "continue", "default", "do", "else",
    "enum", "extends", "false", "final", "finally", "for", "if", "in", "is", "new", "null",
    "rethrow", "return", "super", "switch", "this", "throw", "true", "try", "var", "void",
    "while", "with", "yield",
];

const DART_HELPERS: &str = r#"int _asInt(Object? value) {
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) return int.parse(value);
  throw FormatException('expected int, got $value');
}

int? _asIntOrNull(Object? value) => value == null ? null : _asInt(value);

double _asDouble(Object? value) {
  if (value is double) return value;
  if (value is num) return value.toDouble();
  if (value is String) return double.parse(value);
  throw FormatException('expected double, got $value');
}

double? _asDoubleOrNull(Object? value) => value == null ? null : _asDouble(value);

bool _asBool(Object? value) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  if (value is String) {
    switch (value.toLowerCase()) {
      case 'true':
      case '1':
        return true;
      case 'false':
      case '0':
        return false;
    }
  }
  throw FormatException('expected bool, got $value');
}

bool? _asBoolOrNull(Object? value) => value == null ? null : _asBool(value);

DateTime _asDateTime(Object? value) {
  if (value is DateTime) return value;
  if (value is String) return DateTime.parse(value);
  if (value is int) return DateTime.fromMillisecondsSinceEpoch(value, isUtc: true);
  throw FormatException('expected DateTime, got $value');
}

DateTime? _asDateTimeOrNull(Object? value) =>
    value == null ? null : _asDateTime(value);

String _asString(Object? value) {
  if (value is String) return value;
  if (value == null) throw FormatException('expected String, got null');
  return value.toString();
}

String? _asStringOrNull(Object? value) => value == null ? null : _asString(value);

Map<String, Object?> _asJsonMap(Object? value) {
  if (value is Map<String, Object?>) return value;
  if (value is Map) {
    return value.map((key, nested) => MapEntry(key.toString(), nested));
  }
  throw FormatException('expected JSON object, got $value');
}

Map<String, Object?>? _asJsonMapOrNull(Object? value) =>
    value == null ? null : _asJsonMap(value);

List<double> _asDoubleList(Object? value) {
  if (value is List<double>) return value;
  if (value is List) {
    return value.map(_asDouble).toList();
  }
  throw FormatException('expected List<double>, got $value');
}

List<double>? _asDoubleListOrNull(Object? value) =>
    value == null ? null : _asDoubleList(value);
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::workflow::schema::load::parse_sql_schema;

    #[test]
    fn generates_table_specs_and_row_codecs_from_sql() {
        let snapshot = parse_sql_schema(
            r#"
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL,
  created_at TIMESTAMP
);
"#,
        )
        .unwrap();
        let source = generate_dart_source(&snapshot);
        assert!(source.contains("Generated by kalam schema gen"));
        assert!(!source.to_lowercase().contains("placeholder"));
        assert!(source.contains("import 'package:kalam_sync/kalam_sync.dart';"));
        assert!(source.contains("final class Users {"));
        assert!(source.contains("required this.id"));
        assert!(source.contains("required this.email"));
        assert!(source.contains("this.createdAt"));
        assert!(source.contains("factory Users.fromJson"));
        assert!(source.contains("static final users = KalamTableSpec<Users>("));
        assert!(source.contains("tableId: 'users'"));
        assert!(source.contains("keyColumn: 'id'"));
        assert!(source.contains("mode: KalamSyncMode.bidirectional"));
        assert!(source.contains("keyOf: (row) => row.kalamRowKey"));
        assert!(source.contains("encode: (row) => row.toJson()"));
        assert!(source.contains("decode: Users.fromJson"));
    }

    #[test]
    fn stream_tables_use_replica_only_mode() {
        let snapshot = parse_sql_schema(
            r#"
CREATE STREAM TABLE app.message_events (
  id TEXT PRIMARY KEY,
  payload JSON
);
"#,
        )
        .unwrap();
        let source = generate_dart_source(&snapshot);
        assert!(source.contains("tableId: 'app.message_events'"));
        assert!(source.contains("final class MessageEvents {"));
        assert!(source.contains("static final messageEvents = KalamTableSpec<MessageEvents>("));
        assert!(source.contains("mode: KalamSyncMode.replicaOnly"));
        assert!(source.contains("Map<String, Object?>? payload"));
    }

    #[test]
    fn file_and_jsonb_columns_use_map_codecs() {
        let snapshot = parse_sql_schema(
            r#"
CREATE TABLE IF NOT EXISTS public.messages (
  id TEXT PRIMARY KEY,
  content JSONB NOT NULL,
  attachment FILE
) USING kalamdb WITH (type = 'user');
"#,
        )
        .unwrap();
        let source = generate_dart_source(&snapshot);
        assert!(source.contains("tableId: 'public.messages'"));
        assert!(source.contains("Map<String, Object?> content"));
        assert!(source.contains("Map<String, Object?>? attachment"));
        assert!(source.contains("mode: KalamSyncMode.bidirectional"));
    }

    #[test]
    fn empty_schema_emits_compilable_kalam_tables() {
        let snapshot = parse_sql_schema("-- no tables yet\n").unwrap();
        let source = generate_dart_source(&snapshot);
        assert!(source.contains("abstract final class KalamTables"));
        assert!(!source.contains("KalamTableSpec<"));
        assert!(!source.contains("static final"));
    }

    #[test]
    fn write_dart_schema_creates_parent_directories() {
        let temp = tempfile::TempDir::new().unwrap();
        let output = temp.path().join("lib/generated/kalam.dart");
        let snapshot = parse_sql_schema(
            "CREATE TABLE todos (id TEXT PRIMARY KEY, title TEXT NOT NULL, done BOOLEAN NOT NULL);",
        )
        .unwrap();
        write_dart_schema(&output, &snapshot).unwrap();
        let source = std::fs::read_to_string(&output).unwrap();
        assert!(source.contains("KalamTableSpec<Todos>"));
        assert!(source.contains("bool done"));
    }
}
