//! Schema generation handlers.

use std::path::Path;

use kalam_client::AuthProvider;

use crate::{
    error::{CLIError, Result},
    output::WorkflowOutput,
    process::{resolve_node_binary, run_program_configured, shell_working_directory},
    workflow::{
        auth::resolve_workflow_auth_provider,
        project::resolve::ResolvedEnvironment,
        schema::model::{parse_language_list, LanguageTarget},
        WorkflowContext,
    },
};

const ORM_CODEGEN_SCRIPT: &str = include_str!("../../../assets/orm-codegen.mjs");

pub struct GenerateOptions {
    pub languages: Option<Vec<String>>,
}

pub fn generate_schema_artifacts(
    ctx: &WorkflowContext,
    options: &GenerateOptions,
    output: &WorkflowOutput,
) -> Result<()> {
    let languages = options
        .languages
        .as_ref()
        .map(|values| parse_language_list(values))
        .unwrap_or_else(|| parse_language_list(&ctx.config.schema.languages));

    if languages.is_empty() {
        return Err(CLIError::ConfigurationError(
            "no language targets selected for generation".into(),
        ));
    }

    let mut resolved_environment: Option<ResolvedEnvironment> = None;
    for language in languages {
        let key = language.as_str();
        let Some(target) = ctx.config.schema.targets.get(key) else {
            return Err(CLIError::ConfigurationError(format!(
                "missing schema.targets.{key} in kalam.toml"
            )));
        };

        let output_path = ctx.project_root.join(&target.output);
        match language {
            LanguageTarget::TypeScript => {
                if resolved_environment.is_none() {
                    resolved_environment = Some(ctx.resolved_environment()?);
                }
                let environment =
                    resolved_environment.as_ref().expect("resolved environment initialized");
                generate_typescript_via_orm(ctx, environment, &output_path)?;
            },
            LanguageTarget::Dart => write_dart_placeholder(&output_path)?,
        }
        output.status(format!("generated {} -> {}", key, target.output));
    }

    Ok(())
}

fn generate_typescript_via_orm(
    ctx: &WorkflowContext,
    environment: &ResolvedEnvironment,
    output_path: &Path,
) -> Result<()> {
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let auth = resolve_typescript_codegen_auth(ctx, environment)?;
    let output = run_program_configured(Path::new(&resolve_node_binary()), |command| {
        command
            .current_dir(shell_working_directory(&ctx.project_root))
            .args(node_codegen_args())
            .arg("-e")
            .arg(ORM_CODEGEN_SCRIPT)
            .env("KALAM_SCHEMA_URL", &environment.url)
            .env("KALAM_SCHEMA_NAMESPACE", environment.namespace.as_str())
            .env("KALAM_SCHEMA_OUT", output_path);

        match auth {
            OrmCodegenAuth::Basic { user, password } => {
                command
                    .env("KALAM_SCHEMA_AUTH_MODE", "basic")
                    .env("KALAM_SCHEMA_USER", user)
                    .env("KALAM_SCHEMA_PASSWORD", password);
            },
            OrmCodegenAuth::Jwt { token } => {
                command.env("KALAM_SCHEMA_AUTH_MODE", "jwt").env("KALAM_SCHEMA_TOKEN", token);
            },
            OrmCodegenAuth::None => {
                command.env("KALAM_SCHEMA_AUTH_MODE", "none");
            },
        }
    })
    .map_err(|error| {
        if error.kind() == std::io::ErrorKind::NotFound {
            CLIError::ConfigurationError(
                "Node.js is required for TypeScript schema generation via @kalamdb/orm".into(),
            )
        } else {
            CLIError::FileError(format!("failed to launch @kalamdb/orm generator: {error}"))
        }
    })?;

    if output.status.success() {
        return Ok(());
    }

    let stderr = String::from_utf8_lossy(&output.stderr);
    let stdout = String::from_utf8_lossy(&output.stdout);
    Err(CLIError::ConfigurationError(format!(
        "TypeScript schema generation failed (exit {}): {}{}",
        output.status.code().unwrap_or(-1),
        if stdout.trim().is_empty() {
            String::new()
        } else {
            format!("\nstdout:\n{stdout}")
        },
        if stderr.trim().is_empty() {
            String::new()
        } else {
            format!("\nstderr:\n{stderr}")
        }
    )))
}

fn write_dart_placeholder(output_path: &Path) -> Result<()> {
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(
        output_path,
        "// Placeholder generated by kalam schema gen.\n// Dart schema generation via a dedicated package will be added later.\n",
    )
    .map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", output_path.display()))
    })?;
    Ok(())
}

fn node_codegen_args() -> &'static [&'static str] {
    &["--preserve-symlinks", "--input-type=module"]
}

enum OrmCodegenAuth {
    Basic { user: String, password: String },
    Jwt { token: String },
    None,
}

fn resolve_typescript_codegen_auth(
    ctx: &WorkflowContext,
    environment: &ResolvedEnvironment,
) -> Result<OrmCodegenAuth> {
    match resolve_workflow_auth_provider(ctx, environment)? {
        AuthProvider::JwtToken(token) => Ok(OrmCodegenAuth::Jwt { token }),
        AuthProvider::BasicAuth(user, password) => Ok(OrmCodegenAuth::Basic { user, password }),
        AuthProvider::None => Ok(OrmCodegenAuth::None),
    }
}

pub fn validate_language_filter(
    requested: &[String],
    configured: &[String],
) -> Result<Vec<String>> {
    for value in requested {
        if LanguageTarget::parse(value).is_none() {
            return Err(CLIError::ConfigurationError(format!(
                "unsupported language target '{value}'; supported: typescript, dart"
            )));
        }
        if !configured.iter().any(|lang| lang == value) {
            return Err(CLIError::ConfigurationError(format!(
                "language '{value}' is not enabled in kalam.toml schema.languages"
            )));
        }
    }
    Ok(requested.to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn node_codegen_args_preserve_project_symlink_resolution() {
        assert!(node_codegen_args().contains(&"--preserve-symlinks"));
    }
}
