//! Shared writes and headers for generated schema artifacts.

use std::{fs, io, path::Path};

use kalamdb_sql::contracts::{ContractSnapshot, ContractTable};
use serde::Serialize;

use crate::{
    error::{CLIError, Result},
    workflow::schema::{
        naming::{contract_hash_line, AssignedNames},
        procedures::ProcedureCatalog,
    },
};

pub const GENERATED_HEADER: &str = "// Generated by kalam schema gen. Do not edit.";

#[derive(Debug, Serialize)]
pub struct GeneratedHeader {
    pub header:             &'static str,
    pub contract_hash_line: String,
}

impl GeneratedHeader {
    pub fn from_hash(hash: &str) -> Self {
        Self {
            header:             GENERATED_HEADER,
            contract_hash_line: contract_hash_line(hash),
        }
    }
}

/// Input every language adapter receives from `schema gen`.
///
/// Table/row codecs stay language-specific. Procedure clients and contract
/// types should be derived from [`ProcedureCatalog`] so a new language does
/// not reimplement CALL SQL, namespace grouping, or request/result names.
pub struct SchemaEmitInput<'a> {
    pub project_root: &'a Path,
    pub output_path:  &'a Path,
    pub snapshot:     &'a ContractSnapshot,
    pub hash:         &'a str,
    pub names:        &'a AssignedNames,
    pub procedures:   &'a ProcedureCatalog<'a>,
}

pub fn write_text(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            CLIError::FileError(format!("failed to create '{}': {error}", parent.display()))
        })?;
    }
    fs::write(path, contents).map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", path.display()))
    })
}

pub fn remove_if_exists(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => {
            Err(CLIError::FileError(format!("failed to remove '{}': {error}", path.display())))
        },
    }
}

pub fn line_docs(comment: Option<&str>, prefix: &str) -> String {
    let Some(text) = comment.map(str::trim).filter(|text| !text.is_empty()) else {
        return String::new();
    };
    let mut out = String::new();
    for line in text.lines() {
        out.push_str(prefix);
        out.push_str(line);
        out.push('\n');
    }
    out
}

pub fn type_comment<'a>(snapshot: &'a ContractSnapshot, type_id: &str) -> Option<&'a str> {
    snapshot.types.get(type_id).and_then(|ty| ty.comment.as_deref())
}

pub fn canonical_row_type_id(table: &ContractTable) -> &str {
    table
        .row_alias_id
        .as_ref()
        .map(|id| id.as_str())
        .unwrap_or_else(|| table.row_type_id.as_str())
}

pub fn row_type_ident<'a>(
    snapshot: &ContractSnapshot,
    names: &'a AssignedNames,
    table_id: &str,
) -> &'a str {
    let canonical = snapshot.tables.get(table_id).map(canonical_row_type_id).unwrap_or(table_id);
    names.type_ident(canonical)
}
