//! Rust types generated from a [`ContractSnapshot`].

use std::{fs, path::Path};

use kalamdb_sql::contracts::{ContractField, ContractSnapshot, ContractTypeKind};

use crate::{
    error::{CLIError, Result},
    workflow::schema::{
        naming::{contract_hash_line, AssignedNames},
        types::{render_field_type, TargetLang},
    },
};

const GENERATED_HEADER: &str = "// Generated by kalam schema gen. Do not edit.";

pub fn write_rust_schema(
    output_path: &Path,
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> Result<()> {
    write_text(output_path, &generate_rust_source(snapshot, hash, names))
}

pub fn generate_rust_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");

    for (id, ty) in &snapshot.types {
        match &ty.kind {
            ContractTypeKind::Enum { labels } => {
                let ident = names.type_ident(id);
                emit_rust_doc(&mut out, ty.comment.as_deref());
                out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
                out.push_str("pub enum ");
                out.push_str(ident);
                out.push_str(" {\n");
                for label in labels {
                    out.push_str("    ");
                    out.push_str(&crate::workflow::schema::naming::pascal_case(label));
                    out.push_str(",\n");
                }
                out.push_str("}\n\n");
            },
            ContractTypeKind::Composite { fields } => {
                emit_struct(&mut out, names.type_ident(id), fields, names, ty.comment.as_deref());
            },
            ContractTypeKind::ImplicitTableRow { .. }
            | ContractTypeKind::RowAlias { .. }
            | ContractTypeKind::TopicPayload { .. } => {},
        }
    }

    for table in snapshot.tables.values() {
        let canonical_id = table
            .row_alias_id
            .as_ref()
            .map(|id| id.as_str().to_string())
            .unwrap_or_else(|| table.row_type_id.as_str().to_string());
        emit_struct(
            &mut out,
            names.type_ident(&canonical_id),
            &table.fields,
            names,
            rust_type_comment(snapshot, &canonical_id)
                .or_else(|| rust_type_comment(snapshot, table.row_type_id.as_str())),
        );
        if let Some(alias) = &table.row_alias_id {
            let alias_ident = names.type_ident(alias.as_str());
            let row_ident = names.type_ident(table.row_type_id.as_str());
            if alias_ident != row_ident {
                out.push_str("pub type ");
                out.push_str(row_ident);
                out.push_str(" = ");
                out.push_str(alias_ident);
                out.push_str(";\n\n");
            }
        }
    }

    for (id, ty) in &snapshot.types {
        if let ContractTypeKind::TopicPayload { sources, .. } = &ty.kind {
            emit_topic_payload_enum(&mut out, names.type_ident(id), sources, snapshot, names);
        }
    }

    for (id, routine) in &snapshot.routines {
        let ident = names.routine_ident(id);
        emit_rust_doc(&mut out, routine.comment.as_deref());
        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str("pub struct ");
        out.push_str(ident);
        out.push_str("Input {\n");
        for field in &routine.parameters {
            emit_struct_field(&mut out, field, names);
        }
        out.push_str("}\n\n");
        out.push_str("pub type ");
        out.push_str(ident);
        out.push_str("Output = ");
        match &routine.return_type {
            Some(ret) => out.push_str(&render_field_type(ret, names, TargetLang::Rust)),
            None => out.push_str("()"),
        }
        out.push_str(";\n\n");
    }

    out
}

fn emit_topic_payload_enum(
    out: &mut String,
    ident: &str,
    sources: &[String],
    snapshot: &ContractSnapshot,
    names: &AssignedNames,
) {
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub enum ");
    out.push_str(ident);
    out.push_str(" {\n");
    for table_id in sources {
        let variant = rust_table_variant(snapshot, names, table_id);
        out.push_str("    ");
        out.push_str(variant);
        out.push_str("(");
        out.push_str(variant);
        out.push_str("),\n");
    }
    out.push_str("}\n\n");
}

fn rust_table_variant<'a>(
    snapshot: &ContractSnapshot,
    names: &'a AssignedNames,
    table_id: &str,
) -> &'a str {
    let canonical = snapshot
        .tables
        .get(table_id)
        .and_then(|table| table.row_alias_id.as_ref().map(|id| id.as_str()))
        .unwrap_or(table_id);
    names.type_ident(canonical)
}

fn emit_struct(
    out: &mut String,
    ident: &str,
    fields: &[ContractField],
    names: &AssignedNames,
    comment: Option<&str>,
) {
    emit_rust_doc(out, comment);
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub struct ");
    out.push_str(ident);
    out.push_str(" {\n");
    for field in fields {
        emit_struct_field(out, field, names);
    }
    out.push_str("}\n\n");
}

fn rust_type_comment<'a>(snapshot: &'a ContractSnapshot, type_id: &str) -> Option<&'a str> {
    snapshot.types.get(type_id).and_then(|ty| ty.comment.as_deref())
}

fn emit_rust_doc(out: &mut String, comment: Option<&str>) {
    let Some(text) = comment.map(str::trim).filter(|text| !text.is_empty()) else {
        return;
    };
    for line in text.lines() {
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
}

fn emit_struct_field(out: &mut String, field: &ContractField, names: &AssignedNames) {
    out.push_str("    pub ");
    out.push_str(&rust_field_name(&field.name));
    out.push_str(": ");
    out.push_str(&render_field_type(field, names, TargetLang::Rust));
    out.push_str(",\n");
}

fn rust_field_name(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait",
        "true", "type", "unsafe", "use", "where", "while",
    ];
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn write_text(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            CLIError::FileError(format!("failed to create '{}': {error}", parent.display()))
        })?;
    }
    fs::write(path, contents).map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", path.display()))
    })
}

#[cfg(test)]
mod tests {
    use kalamdb_sql::compile_contract_sql;

    use super::*;
    use crate::workflow::schema::naming::{assign_names, NamingOptions};

    #[test]
    fn rust_reuses_alias_and_nests_struct_fields() {
        let snapshot = compile_contract_sql(
            "CREATE SCHEMA chat;
             CREATE TYPE chat.address AS (city TEXT, country TEXT);
             CREATE TABLE chat.users (
               id BIGINT PRIMARY KEY,
               address chat.address,
               nickname TEXT
             ) ROW TYPE chat.user;",
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_rust_source(&snapshot, &hash, &names);
        assert!(source.contains(&format!("contract_hash: {hash}")));
        assert!(source.contains("pub struct ChatAddress"));
        assert!(source.contains("pub struct ChatUser"));
        assert!(source.contains("pub type ChatUsers = ChatUser;"));
        assert!(source.contains("pub address: Option<ChatAddress>"));
        assert!(source.contains("pub nickname: Option<String>"));
        assert!(source.contains("pub id: i64"));
    }

    #[test]
    fn topic_payload_emits_enum_after_table_structs() {
        let snapshot = compile_contract_sql(
            r#"
CREATE SCHEMA chat;
CREATE TABLE chat.messages (id BIGINT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE chat.direct_messages (id BIGINT PRIMARY KEY, body TEXT NOT NULL);
CREATE TOPIC chat.ai_inbox;
ALTER TOPIC chat.ai_inbox ADD SOURCE chat.messages ON INSERT;
ALTER TOPIC chat.ai_inbox ADD SOURCE chat.direct_messages ON INSERT;
"#,
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_rust_source(&snapshot, &hash, &names);
        let messages = source.find("pub struct ChatMessages").expect(source.as_str());
        let inbox = source.find("pub enum ChatAiInbox").expect(source.as_str());
        assert!(inbox > messages, "{source}");
        assert!(source.contains("ChatDirectMessages(ChatDirectMessages)"));
        assert!(source.contains("ChatMessages(ChatMessages)"));
    }

    #[test]
    fn comments_emit_rust_docs() {
        let snapshot = compile_contract_sql(
            "CREATE SCHEMA chat;
             CREATE TYPE chat.address AS (city TEXT NOT NULL) COMMENT 'Postal address';
             CREATE PROCEDURE chat.ping() RETURNS TEXT COMMENT 'Liveness probe';",
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_rust_source(&snapshot, &hash, &names);
        assert!(source.contains("/// Postal address"), "{source}");
        assert!(source.contains("/// Liveness probe"), "{source}");
    }
}
