//! TypeScript client, server contracts, and one-shot procedure scaffolds.

use std::{
    collections::{BTreeMap, HashSet},
    fs, io,
    path::{Path, PathBuf},
};

use kalamdb_functions_host::{
    emit_procedure_builder_dts, emit_procedure_builder_js, emit_typed_functions_host,
    emit_typescript, TypedRoutine,
};
use kalamdb_sql::contracts::{
    table_payload_tag, ContractField, ContractRoutine, ContractSnapshot, ContractTable,
    ContractTableKind, ContractTypeKind,
};

use crate::{
    error::{CLIError, Result},
    workflow::schema::{
        naming::{
            contract_hash_line, method_ident, namespace_object_ident, value_ident, AssignedNames,
        },
        procedure_bindings::{discover_procedure_bindings, ProcedureBinding},
        types::{render_field_type, TargetLang},
    },
};

const FUNCTIONS_DIR: &str = "functions";
const GENERATED_HEADER: &str = "// Generated by kalam schema gen. Do not edit.";

pub fn write_typescript(
    output_path: &Path,
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
    project_root: &Path,
) -> Result<()> {
    let schema_path = output_path.with_file_name("schema.ts");
    write_text(&schema_path, &generate_schema_source(snapshot, hash, names))?;
    write_text(output_path, &generate_client_source(snapshot, hash, names))?;
    write_procedure_artifacts(project_root, &schema_path, snapshot, hash, names)?;
    Ok(())
}

pub fn generate_schema_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");

    let needs_orm = !snapshot.tables.is_empty();
    if needs_orm {
        out.push_str("import { kTable } from '@kalamdb/orm';\n");
        out.push_str(
            "import { integer, text, timestamp, boolean, jsonb, bigint } from \
             'drizzle-orm/pg-core';\n\n",
        );
    }

    out.push_str(
        "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: \
         string]: JsonValue };\n\n",
    );
    emit_shared_types(&mut out, snapshot, names, "export ");
    emit_ktables(&mut out, snapshot);
    out
}

pub fn generate_client_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");
    out.push_str("export * from './schema';\n");
    let mut type_imports: Vec<String> = Vec::new();
    for (id, routine) in &snapshot.routines {
        let ident = names.routine_ident(id);
        if !routine.parameters.is_empty() {
            type_imports.push(procedure_request_ident(ident));
        }
        type_imports.push(procedure_result_ident(ident));
    }
    if !type_imports.is_empty() {
        out.push_str("import type { ");
        out.push_str(&type_imports.join(", "));
        out.push_str(" } from './schema';\n");
    }
    out.push('\n');
    emit_frontend_client(&mut out, snapshot, names);
    out
}

pub fn generate_contracts_source(hash: &str, schema_import: &str) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");
    out.push_str("export * from \"");
    out.push_str(schema_import);
    out.push_str("\";\n");
    out.push_str("export type { ProcedureContext } from \"./runtime\";\n");
    out.push_str("export { procedure } from \"./procedure.js\";\n");
    out
}

pub fn generate_runtime_dts(
    snapshot: &ContractSnapshot,
    names: &AssignedNames,
    schema_import: &str,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\n\n");
    out.push_str(&emit_typescript());
    out.push_str(&emit_typed_functions_host(&typed_routines(snapshot, names), schema_import));
    out
}

pub fn generate_runtime_js() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(
        r#"
import { bindFunctionOrm } from "@kalamdb/orm";

export function wrapProcedure(handler) {
  return (ctx, input) => {
    if (Object.prototype.hasOwnProperty.call(ctx, "orm")) {
      return handler(ctx, input);
    }
    const next = Object.create(ctx);
    Object.defineProperty(next, "orm", {
      value: bindFunctionOrm(ctx.db),
      enumerable: true,
    });
    return handler(Object.freeze(next), input);
  };
}
"#,
    );
    out
}

pub fn generate_procedure_dts(
    snapshot: &ContractSnapshot,
    names: &AssignedNames,
    schema_import: &str,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\n\n");
    out.push_str(&emit_procedure_builder_dts(&typed_routines(snapshot, names), schema_import));
    out
}

pub fn generate_procedure_js(snapshot: &ContractSnapshot, names: &AssignedNames) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str(&emit_procedure_builder_js(&typed_routines(snapshot, names)));
    out
}

fn typed_routines<'a>(
    snapshot: &'a ContractSnapshot,
    names: &'a AssignedNames,
) -> Vec<TypedRoutine<'a>> {
    snapshot
        .routines
        .values()
        .map(|routine| TypedRoutine {
            namespace:   routine.schema.as_str(),
            name:        routine.name.as_str(),
            type_ident:  names.routine_ident(routine.routine_id.as_str()),
            param_count: routine.parameters.len(),
        })
        .collect()
}

fn emit_shared_types(
    out: &mut String,
    snapshot: &ContractSnapshot,
    names: &AssignedNames,
    export: &str,
) {
    for (id, ty) in &snapshot.types {
        match &ty.kind {
            ContractTypeKind::Enum { labels } => {
                let ident = names.type_ident(id);
                let union = labels
                    .iter()
                    .map(|label| format!("\"{}\"", escape_ts_string(label)))
                    .collect::<Vec<_>>()
                    .join(" | ");
                emit_jsdoc(out, ty.comment.as_deref(), "");
                let _ = writeln_str(out, &format!("{export}type {ident} = {union};\n"));
            },
            ContractTypeKind::Composite { fields } => {
                emit_object_type(
                    out,
                    export,
                    names.type_ident(id),
                    fields,
                    names,
                    ty.comment.as_deref(),
                );
            },
            ContractTypeKind::TopicPayload { .. }
            | ContractTypeKind::ImplicitTableRow { .. }
            | ContractTypeKind::RowAlias { .. } => {},
        }
    }

    for table in snapshot.tables.values() {
        let canonical_id = table
            .row_alias_id
            .as_ref()
            .map(|id| id.as_str().to_string())
            .unwrap_or_else(|| table.row_type_id.as_str().to_string());
        let comment = type_comment(snapshot, &canonical_id)
            .or_else(|| type_comment(snapshot, table.row_type_id.as_str()));
        emit_object_type(
            out,
            export,
            names.type_ident(&canonical_id),
            &table.fields,
            names,
            comment,
        );
        if let Some(alias) = &table.row_alias_id {
            let alias_ident = names.type_ident(alias.as_str());
            let row_ident = names.type_ident(table.row_type_id.as_str());
            if alias_ident != row_ident {
                let _ = writeln_str(out, &format!("{export}type {row_ident} = {alias_ident};\n"));
            }
        }
    }

    for (id, ty) in &snapshot.types {
        if let ContractTypeKind::TopicPayload { sources, .. } = &ty.kind {
            emit_topic_payload_type(
                out,
                export,
                names.type_ident(id),
                sources,
                snapshot,
                names,
                ty.comment.as_deref(),
            );
        }
    }

    for (id, routine) in &snapshot.routines {
        emit_procedure_type(out, export, names.routine_ident(id), routine, names);
    }
}

fn emit_topic_payload_type(
    out: &mut String,
    export: &str,
    ident: &str,
    sources: &[String],
    snapshot: &ContractSnapshot,
    names: &AssignedNames,
    comment: Option<&str>,
) {
    emit_jsdoc(out, comment, "");
    out.push_str(export);
    out.push_str("type ");
    out.push_str(ident);
    if sources.is_empty() {
        out.push_str(" = never;\n\n");
        return;
    }
    out.push_str(" =\n");
    for (index, table_id) in sources.iter().enumerate() {
        let tag = table_payload_tag(table_id);
        let row_ident = table_row_ident(snapshot, names, table_id);
        out.push_str("  | ({ _table: \"");
        out.push_str(&escape_ts_string(&tag));
        out.push_str("\" } & ");
        out.push_str(row_ident);
        out.push(')');
        if index + 1 == sources.len() {
            out.push_str(";\n\n");
        } else {
            out.push('\n');
        }
    }
}

fn table_row_ident<'a>(
    snapshot: &ContractSnapshot,
    names: &'a AssignedNames,
    table_id: &str,
) -> &'a str {
    let canonical = snapshot
        .tables
        .get(table_id)
        .and_then(|table| table.row_alias_id.as_ref().map(|id| id.as_str()))
        .unwrap_or(table_id);
    names.type_ident(canonical)
}

fn emit_object_type(
    out: &mut String,
    export: &str,
    ident: &str,
    fields: &[ContractField],
    names: &AssignedNames,
    comment: Option<&str>,
) {
    emit_jsdoc(out, comment, "");
    out.push_str(export);
    out.push_str("type ");
    out.push_str(ident);
    out.push_str(" = {\n");
    for field in fields {
        let ty = render_field_type(field, names, TargetLang::TypeScript);
        out.push_str("  ");
        out.push_str(&field.name);
        out.push_str(": ");
        out.push_str(&ty);
        out.push_str(";\n");
    }
    out.push_str("};\n\n");
}

fn emit_procedure_type(
    out: &mut String,
    export: &str,
    ident: &str,
    routine: &ContractRoutine,
    names: &AssignedNames,
) {
    let request = procedure_request_ident(ident);
    let result = procedure_result_ident(ident);
    emit_jsdoc(out, routine.comment.as_deref(), "");
    out.push_str(export);
    out.push_str("type ");
    out.push_str(&request);
    if routine.parameters.is_empty() {
        out.push_str(" = Record<string, never>;\n\n");
    } else {
        out.push_str(" = {\n");
        for field in &routine.parameters {
            let ty = render_field_type(field, names, TargetLang::TypeScript);
            out.push_str("  ");
            out.push_str(&field.name);
            out.push_str(": ");
            out.push_str(&ty);
            out.push_str(";\n");
        }
        out.push_str("};\n\n");
    }
    emit_jsdoc(out, routine.comment.as_deref(), "");
    out.push_str(export);
    out.push_str("type ");
    out.push_str(&result);
    out.push_str(" = ");
    match &routine.return_type {
        Some(ret) => out.push_str(&render_field_type(ret, names, TargetLang::TypeScript)),
        None => out.push_str("void"),
    }
    out.push_str(";\n\n");
}

fn procedure_request_ident(ident: &str) -> String {
    format!("{ident}Request")
}

fn procedure_result_ident(ident: &str) -> String {
    format!("{ident}Result")
}

fn emit_ktables(out: &mut String, snapshot: &ContractSnapshot) {
    for table in snapshot.tables.values() {
        let var_name = value_ident(&table.schema, &table.name, false);
        let table_name = wire_table_name(table);
        let factory = match table.kind {
            ContractTableKind::User => "kTable.user",
            ContractTableKind::Shared => "kTable.shared",
            ContractTableKind::Stream => "kTable.stream",
            ContractTableKind::Unspecified => "kTable",
        };
        out.push_str("export const ");
        out.push_str(&var_name);
        out.push_str(" = ");
        out.push_str(factory);
        out.push_str("(");
        out.push_str(&format!("\"{}\"", escape_ts_string(&table_name)));
        out.push_str(", {\n");
        for field in &table.fields {
            out.push_str("  ");
            out.push_str(&field.name);
            out.push_str(": ");
            out.push_str(&drizzle_column(field));
            out.push_str(",\n");
        }
        out.push_str("});\n\n");
    }
}

fn drizzle_column(field: &ContractField) -> String {
    let mut expr = if field.type_id.is_some() {
        format!("jsonb(\"{}\")", escape_ts_string(&field.name))
    } else {
        let sql = field.type_name.to_ascii_uppercase();
        match sql.as_str() {
            "BOOLEAN" | "BOOL" => format!("boolean(\"{}\")", escape_ts_string(&field.name)),
            "INT" | "INTEGER" | "INT4" | "SERIAL" | "SMALLINT" | "INT2" => {
                format!("integer(\"{}\")", escape_ts_string(&field.name))
            },
            "BIGINT" | "INT8" | "INT64" | "BIGSERIAL" => {
                format!("bigint(\"{}\", {{ mode: \"bigint\" }})", escape_ts_string(&field.name))
            },
            "TIMESTAMP" | "TIMESTAMPTZ" | "DATETIME" => {
                format!("timestamp(\"{}\", {{ mode: \"date\" }})", escape_ts_string(&field.name))
            },
            "JSON" | "JSONB" | "FILE" => format!("jsonb(\"{}\")", escape_ts_string(&field.name)),
            _ => format!("text(\"{}\")", escape_ts_string(&field.name)),
        }
    };
    if field.name == "id" {
        expr.push_str(".primaryKey()");
    } else if field.not_null {
        expr.push_str(".notNull()");
    }
    expr
}

fn emit_frontend_client(out: &mut String, snapshot: &ContractSnapshot, names: &AssignedNames) {
    out.push_str(
        "export type KalamQueryClient = {\n  query: (sql: string, params?: unknown[]) => \
         Promise<{\n    status?: string;\n    error?: unknown;\n    results?: Array<{\n      \
         rows?: unknown;\n      named_rows?: Array<Record<string, unknown>>;\n    }>;\n  \
         }>;\n};\n\nfunction kalamCallResult(response: \
         Awaited<ReturnType<KalamQueryClient[\"query\"]>>): unknown {\n  const result = \
         response.results?.[0];\n  if (result?.named_rows?.[0] && \"result\" in \
         result.named_rows[0]) {\n    return result.named_rows[0].result;\n  }\n  const rows = \
         result?.rows;\n  if (!Array.isArray(rows) || rows.length === 0) {\n    return \
         undefined;\n  }\n  const first = rows[0];\n  return Array.isArray(first) ? first[0] : \
         first;\n}\n\nexport function createKalam(client: KalamQueryClient) {\n  return {\n",
    );
    let mut by_namespace: BTreeMap<&str, Vec<&ContractRoutine>> = BTreeMap::new();
    for routine in snapshot.routines.values() {
        by_namespace.entry(routine.schema.as_str()).or_default().push(routine);
    }
    for (namespace, routines) in &by_namespace {
        out.push_str("    ");
        out.push_str(&namespace_object_ident(namespace));
        out.push_str(": {\n");
        for routine in routines {
            let method = method_ident(&routine.name);
            let ident = names.routine_ident(routine.routine_id.as_str());
            let request = procedure_request_ident(ident);
            let result = procedure_result_ident(ident);
            emit_jsdoc(out, routine.comment.as_deref(), "      ");
            out.push_str("      ");
            out.push_str(&method);
            if routine.parameters.is_empty() {
                out.push_str(": async (): Promise<");
                out.push_str(&result);
                out.push_str("> => {\n");
            } else {
                out.push_str(": async (input: ");
                out.push_str(&request);
                out.push_str("): Promise<");
                out.push_str(&result);
                out.push_str("> => {\n");
            }
            emit_call_body(out, routine, &result);
            out.push_str("      },\n");
        }
        out.push_str("    },\n");
    }
    out.push_str("  };\n}\n");
}

fn emit_call_body(out: &mut String, routine: &ContractRoutine, result_ident: &str) {
    let qualified = format!("{}.{}", routine.schema, routine.name);
    let params = &routine.parameters;
    match params.len() {
        0 => {
            out.push_str("        const response = await client.query(\"CALL ");
            out.push_str(&qualified);
            out.push_str("()\");\n");
        },
        1 => {
            out.push_str("        const response = await client.query(\"CALL ");
            out.push_str(&qualified);
            out.push_str("($1)\", [input.");
            out.push_str(&params[0].name);
            out.push_str("]);\n");
        },
        _ => {
            out.push_str("        const response = await client.query(\"CALL ");
            out.push_str(&qualified);
            out.push_str("(");
            for index in 0..params.len() {
                if index > 0 {
                    out.push_str(", ");
                }
                out.push('$');
                out.push_str(&(index + 1).to_string());
            }
            out.push_str(")\", [");
            for (index, param) in params.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                out.push_str("input.");
                out.push_str(&param.name);
            }
            out.push_str("]);\n");
        },
    }
    out.push_str("        return kalamCallResult(response) as ");
    out.push_str(result_ident);
    out.push_str(";\n");
}

fn write_procedure_artifacts(
    project_root: &Path,
    schema_path: &Path,
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> Result<()> {
    let generated_dir = project_root.join(FUNCTIONS_DIR).join("src").join("generated");
    let schema_import = ts_relative_module(&generated_dir, schema_path);
    write_text(
        &generated_dir.join("runtime.d.ts"),
        &generate_runtime_dts(snapshot, names, &schema_import),
    )?;
    // Identity helper must be `.js`. A sibling `runtime.ts` shadows `runtime.d.ts`
    // and types `wrapProcedure` as `(handler: any) => any`.
    write_text(&generated_dir.join("runtime.js"), &generate_runtime_js())?;
    remove_if_exists(&generated_dir.join("runtime.ts"))?;
    remove_stale_dot_kalam_generated(project_root)?;
    if snapshot.routines.is_empty() {
        return Ok(());
    }
    write_text(
        &generated_dir.join("procedure.d.ts"),
        &generate_procedure_dts(snapshot, names, &schema_import),
    )?;
    write_text(&generated_dir.join("procedure.js"), &generate_procedure_js(snapshot, names))?;
    remove_if_exists(&generated_dir.join("procedure.ts"))?;
    write_text(
        &generated_dir.join("contracts.ts"),
        &generate_contracts_source(hash, &schema_import),
    )?;

    let bindings = discover_procedure_bindings(project_root, snapshot)?;
    let bound: HashSet<&str> = bindings.iter().map(|binding| binding.routine_id.as_str()).collect();
    for routine in snapshot.routines.values() {
        if is_project_backed_routine(routine) && !bound.contains(routine.routine_id.as_str()) {
            scaffold_procedure(project_root, routine, names)?;
        }
        write_inline_shim(&generated_dir, routine)?;
    }
    let bindings = discover_procedure_bindings(project_root, snapshot)?;
    write_text(
        &generated_dir.join("registry.ts"),
        &generate_registry_source(hash, &bindings, &generated_dir),
    )?;
    Ok(())
}

pub fn generate_registry_source(
    hash: &str,
    bindings: &[ProcedureBinding],
    generated_dir: &Path,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");
    let implemented: Vec<&ProcedureBinding> =
        bindings.iter().filter(|binding| binding.implemented).collect();
    let mut by_file: BTreeMap<&Path, Vec<&ProcedureBinding>> = BTreeMap::new();
    for binding in &implemented {
        by_file.entry(binding.source_path.as_path()).or_default().push(*binding);
    }
    for (path, file_bindings) in &by_file {
        out.push_str("import { ");
        for (index, binding) in file_bindings.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }
            out.push_str(&binding.export_name);
            out.push_str(" as ");
            out.push_str(&value_ident(&binding.schema, &binding.name, false));
        }
        out.push_str(" } from \"");
        out.push_str(&ts_relative_module(generated_dir, path));
        out.push_str("\";\n");
    }
    out.push_str("\nexport const procedures = {\n");
    for binding in implemented {
        out.push_str("  \"");
        out.push_str(&binding.routine_id);
        out.push_str("\": ");
        out.push_str(&value_ident(&binding.schema, &binding.name, false));
        out.push_str(",\n");
    }
    out.push_str("};\n");
    out
}

fn write_inline_shim(generated_dir: &Path, routine: &ContractRoutine) -> Result<()> {
    let Some(body) = routine.body.as_deref() else {
        return Ok(());
    };
    let ident = format!("{}_{}", routine.schema, routine.name);
    let source = format!(
        "{GENERATED_HEADER}\nimport type {{ ProcedureContext }} from \"../runtime\";\n\nexport \
         async function {ident}(ctx: ProcedureContext, input: unknown): Promise<unknown> \
         {{\n{body}\n}}\n"
    );
    write_text(&generated_dir.join("inline").join(format!("{ident}.ts")), &source)
}

fn scaffold_procedure(
    project_root: &Path,
    routine: &ContractRoutine,
    _names: &AssignedNames,
) -> Result<()> {
    let path = procedure_impl_path(project_root, &routine.schema, &routine.name);
    if path.exists() {
        return Ok(());
    }
    write_text(&path, &unimplemented_procedure_source(&routine.schema, &routine.name))
}

pub fn unimplemented_procedure_source(schema: &str, name: &str) -> String {
    let ns = namespace_object_ident(schema);
    let method = method_ident(name);
    format!(
        "import {{ procedure }} from \"../generated/contracts\";\n\nexport const {method} = \
         procedure.{ns}.{method}.unimplemented();\n"
    )
}

pub fn implemented_procedure_source(schema: &str, name: &str, body: Option<&str>) -> String {
    let ns = namespace_object_ident(schema);
    let method = method_ident(name);
    let handler = match body {
        Some(body) if !body.trim().is_empty() => format!("async (ctx, input) => {{\n{body}\n}}"),
        _ => "async (ctx, input) => {\n  return input;\n}".to_string(),
    };
    format!(
        "import {{ procedure }} from \"../generated/contracts\";\n\nexport const {method} = \
         procedure.{ns}.{method}({handler});\n"
    )
}

pub fn procedure_impl_path(project_root: &Path, schema: &str, name: &str) -> PathBuf {
    project_root
        .join(FUNCTIONS_DIR)
        .join("src")
        .join(schema)
        .join(format!("{name}.ts"))
}

fn is_project_backed_routine(routine: &ContractRoutine) -> bool {
    routine.body.is_none() && is_typescript_routine(routine)
}

fn is_typescript_routine(routine: &ContractRoutine) -> bool {
    match routine.language.as_deref() {
        None => true,
        Some(language) => matches!(
            language.to_ascii_uppercase().as_str(),
            "TS" | "TYPESCRIPT" | "JS" | "JAVASCRIPT" | "PLV8"
        ),
    }
}

fn wire_table_name(table: &ContractTable) -> String {
    table.table_id.clone()
}

fn remove_stale_dot_kalam_generated(project_root: &Path) -> Result<()> {
    let stale = project_root.join(FUNCTIONS_DIR).join(".kalam").join("generated");
    if !stale.exists() {
        return Ok(());
    }
    fs::remove_dir_all(&stale).map_err(|error| {
        CLIError::FileError(format!("failed to remove '{}': {error}", stale.display()))
    })
}

fn remove_if_exists(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => {
            Err(CLIError::FileError(format!("failed to remove '{}': {error}", path.display())))
        },
    }
}

fn write_text(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            CLIError::FileError(format!("failed to create '{}': {error}", parent.display()))
        })?;
    }
    fs::write(path, contents).map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", path.display()))
    })
}

fn ts_relative_module(from_dir: &Path, target_file: &Path) -> String {
    let target_stem = target_file.with_extension("");
    let mut from_comps: Vec<_> = from_dir.components().collect();
    let mut to_comps: Vec<_> = target_stem.components().collect();
    while !from_comps.is_empty() && !to_comps.is_empty() && from_comps[0] == to_comps[0] {
        from_comps.remove(0);
        to_comps.remove(0);
    }
    let mut parts: Vec<String> = Vec::new();
    for _ in &from_comps {
        parts.push("..".to_string());
    }
    for component in &to_comps {
        parts.push(component.as_os_str().to_string_lossy().into_owned());
    }
    if parts.is_empty() {
        return "./schema".to_string();
    }
    let joined = parts.join("/");
    if joined.starts_with('.') {
        joined
    } else {
        format!("./{joined}")
    }
}

fn type_comment<'a>(snapshot: &'a ContractSnapshot, type_id: &str) -> Option<&'a str> {
    snapshot.types.get(type_id).and_then(|ty| ty.comment.as_deref())
}

fn emit_jsdoc(out: &mut String, comment: Option<&str>, indent: &str) {
    let Some(text) = comment.map(str::trim).filter(|text| !text.is_empty()) else {
        return;
    };
    let safe = text.replace("*/", "* /");
    if !safe.contains('\n') {
        out.push_str(indent);
        out.push_str("/** ");
        out.push_str(&safe);
        out.push_str(" */\n");
        return;
    }
    out.push_str(indent);
    out.push_str("/**\n");
    for line in safe.lines() {
        out.push_str(indent);
        out.push_str(" * ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(indent);
    out.push_str(" */\n");
}

fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn writeln_str(out: &mut String, value: &str) -> std::fmt::Result {
    out.push_str(value);
    if !value.ends_with('\n') {
        out.push('\n');
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use kalamdb_sql::compile_contract_sql;

    use super::*;
    use crate::workflow::schema::naming::{assign_names, NamingOptions};

    #[test]
    fn client_embeds_hash_nested_client_and_prefixed_types() {
        let snapshot = compile_contract_sql(GOLDEN_SQL, "public").unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let schema = generate_schema_source(&snapshot, &hash, &names);
        let source = generate_client_source(&snapshot, &hash, &names);
        assert!(source.contains(&format!("contract_hash: {hash}")));
        assert!(source.contains("export * from './schema'"));
        assert!(schema.contains("export type ChatAddress"));
        assert!(schema.contains("address: ChatAddress | null"));
        assert!(schema.contains("nickname: string | null"));
        assert!(schema.contains("export type ChatUser"));
        assert!(schema.contains("export type ChatUsers = ChatUser"));
        assert!(schema.contains("export type ChatStatus = \"active\" | \"blocked\""));
        assert!(source.contains("createKalam"));
        assert!(source.contains("CALL chat.create_message($1, $2)"));
        assert!(!source.contains("procedure client has no local runtime"));
        assert!(source.contains("chat: {"));
        assert!(source.contains("createMessage:"));
        assert!(schema.contains("export type ChatCreateMessageRequest"));
        assert!(schema.contains("export type ChatCreateMessageResult"));
        assert!(source.contains("createMessage: async (input: ChatCreateMessageRequest)"));
        assert!(!source.contains("kalam.chat.createMessage"));
        assert!(source.contains("rows?: unknown;"));
        assert!(source.contains("Array.isArray(first) ? first[0] : first"));
    }

    #[test]
    fn topic_payload_emits_tagged_union() {
        let snapshot = compile_contract_sql(
            r#"
CREATE SCHEMA chat;
CREATE TABLE chat.messages (id BIGINT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE chat.direct_messages (id BIGINT PRIMARY KEY, body TEXT NOT NULL);
CREATE TOPIC chat.ai_inbox;
ALTER TOPIC chat.ai_inbox ADD SOURCE chat.messages ON INSERT;
ALTER TOPIC chat.ai_inbox ADD SOURCE chat.direct_messages ON INSERT;
CREATE PROCEDURE chat.on_message(payload chat.ai_inbox NOT NULL)
RETURNS chat.ai_inbox;
"#,
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let schema = generate_schema_source(&snapshot, &hash, &names);
        assert!(schema.contains("export type ChatAiInbox ="), "{schema}");
        assert!(
            schema.contains("({ _table: \"chat:direct_messages\" } & ChatDirectMessages)"),
            "{schema}"
        );
        assert!(schema.contains("({ _table: \"chat:messages\" } & ChatMessages)"), "{schema}");
        assert!(schema.contains("payload: ChatAiInbox;"), "{schema}");
        assert!(
            schema.contains("export type ChatOnMessageResult = ChatAiInbox | null;"),
            "{schema}"
        );
    }

    #[test]
    fn comments_emit_jsdoc() {
        let snapshot = compile_contract_sql(
            r#"
CREATE SCHEMA chat;
CREATE TYPE chat.address AS (city TEXT NOT NULL) COMMENT 'Postal address';
CREATE PROCEDURE chat.ping() RETURNS TEXT COMMENT 'Liveness probe';
"#,
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let schema = generate_schema_source(&snapshot, &hash, &names);
        let client = generate_client_source(&snapshot, &hash, &names);
        assert!(schema.contains("/** Postal address */"), "{schema}");
        assert!(schema.contains("/** Liveness probe */"), "{schema}");
        assert!(client.contains("/** Liveness probe */"), "{client}");
    }

    #[test]
    fn runtime_js_binds_ctx_orm() {
        let js = generate_runtime_js();
        assert!(js.contains("export function wrapProcedure(handler)"));
        assert!(js.contains("import { bindFunctionOrm } from \"@kalamdb/orm\""));
        assert!(js.contains("bindFunctionOrm(ctx.db)"));
        assert!(js.contains("next, \"orm\""));
    }

    #[test]
    fn contracts_import_schema_relatively() {
        let from = PathBuf::from("/proj/functions/src/generated");
        let target = PathBuf::from("/proj/src/generated/schema.ts");
        assert_eq!(ts_relative_module(&from, &target), "../../../src/generated/schema");
    }

    const GOLDEN_SQL: &str = r#"
CREATE SCHEMA chat;
CREATE TYPE chat.address AS (city TEXT, country TEXT);
CREATE TYPE chat.status AS ENUM ('active', 'blocked');
CREATE TABLE chat.users (
  id BIGINT PRIMARY KEY,
  email TEXT NOT NULL,
  address chat.address,
  nickname TEXT,
  status chat.status NOT NULL
) ROW TYPE chat.user;
CREATE PROCEDURE chat.create_message(user_id TEXT, body TEXT NOT NULL)
RETURNS chat.user;
"#;
}
