import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const exampleRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

async function readExample(relativePath: string): Promise<string> {
  return readFile(resolve(exampleRoot, relativePath), 'utf8');
}

test('chat-with-ai is a kalam CLI project with generated TypeScript in src/generated', async () => {
  const kalamToml = await readExample('kalam.toml');
  const packageJson = await readExample('package.json');
  const schemaSql = await readExample('kalam/schema.sql');
  const app = await readExample('src/App.tsx');
  const sendMessage = await readExample('functions/src/chat_demo/send_message.ts');
  const joinRoom = await readExample('functions/src/chat_demo/join_room.ts');
  const onUserMessage = await readExample('functions/src/chat_demo/on_user_message.ts');
  const generated = await readExample('src/generated/kalam.ts');
  const schema = await readExample('src/generated/schema.ts');

  assert.match(kalamToml, /path = "kalam\/schema\.sql"/);
  assert.match(kalamToml, /output = "src\/generated\/kalam\.ts"/);
  assert.match(kalamToml, /generate_types = true/);
  assert.match(kalamToml, /app = "npm run dev"/);
  assert.match(kalamToml, /\[functions\]/);
  assert.doesNotMatch(kalamToml, /agent = "npm run agent"/);

  assert.doesNotMatch(packageJson, /"setup"/);
  assert.doesNotMatch(packageJson, /"agent"/);
  assert.doesNotMatch(packageJson, /@kalamdb\/consumer/);
  assert.equal(existsSync(resolve(exampleRoot, 'src/agent.ts')), false);
  assert.equal(existsSync(resolve(exampleRoot, 'functions/src/chat_demo/chat.ts')), false);
  assert.equal(existsSync(resolve(exampleRoot, 'functions/src/chat_demo/send_message.ts')), true);
  assert.equal(existsSync(resolve(exampleRoot, 'functions/src/chat_demo/join_room.ts')), true);
  assert.equal(existsSync(resolve(exampleRoot, 'functions/src/chat_demo/on_user_message.ts')), true);
  assert.equal(existsSync(resolve(exampleRoot, 'setup.mjs')), false);
  assert.equal(existsSync(resolve(exampleRoot, 'scripts/generate-schema.mjs')), false);
  assert.equal(existsSync(resolve(exampleRoot, 'src/schema.generated.ts')), false);

  assert.match(schemaSql, /CREATE SHARED TABLE IF NOT EXISTS chat_demo\.room_members/);
  assert.match(schemaSql, /CREATE USER TABLE IF NOT EXISTS chat_demo\.direct_messages/);
  assert.match(schemaSql, /id TEXT PRIMARY KEY/);
  assert.doesNotMatch(schemaSql, /PRIMARY KEY \(user_id, room_id\)/);
  assert.match(schemaSql, /CREATE POLICY rooms_visible/);
  assert.match(schemaSql, /CREATE POLICY messages_member_select/);
  assert.doesNotMatch(schemaSql, /CREATE POLICY rooms_member_select/);
  assert.match(schemaSql, /CREATE STREAM TABLE IF NOT EXISTS chat_demo\.agent_events/);
  assert.match(schemaSql, /CREATE PROCEDURE chat_demo\.send_message/);
  assert.match(schemaSql, /RETURNS chat_demo\.ai_inbox/);
  assert.match(schemaSql, /payload chat_demo\.ai_inbox NOT NULL/);
  assert.match(schemaSql, /CREATE TRIGGER chat_demo\.process_user_message/);
  assert.match(schemaSql, /ALTER TOPIC chat_demo\.ai_inbox ADD SOURCE chat_demo\.messages ON INSERT/);
  assert.match(schemaSql, /ALTER TOPIC chat_demo\.ai_inbox ADD SOURCE chat_demo\.direct_messages ON INSERT/);

  assert.match(app, /from '\.\/generated\/kalam'/);
  assert.match(app, /liveTable/);
  assert.match(app, /api\.chatDemo\.sendMessage/);
  assert.match(app, /api\.chatDemo\.joinRoom/);
  assert.match(sendMessage, /procedure\.chatDemo\.sendMessage/);
  assert.match(joinRoom, /procedure\.chatDemo\.joinRoom/);
  assert.match(onUserMessage, /procedure\.chatDemo\.onUserMessage/);
  assert.match(sendMessage, /insert\(chatDemoMessages\)/);
  assert.match(sendMessage, /insert\(chatDemoDirectMessages\)/);
  assert.match(sendMessage, /taggedRow\("chat_demo:direct_messages"/);
  assert.match(sendMessage, /taggedRow\("chat_demo:messages"/);
  assert.match(generated, /Generated by kalam schema gen/);
  assert.doesNotMatch(generated, /Generated by @kalamdb\/orm/);
  assert.match(generated, /export \* from '\.\/schema'/);
  assert.match(generated, /export function createKalam/);
  assert.match(generated, /response\.status === "error"/);
  assert.match(generated, /throw new Error\(kalamCallErrorMessage\(response\.error\)\)/);
  assert.match(schema, /export const chatDemoMessages = kTable.shared/);
  assert.match(schema, /export const chatDemoDirectMessages = kTable.user/);
  assert.match(schema, /export const chatDemoAgentEvents = kTable.stream/);
  assert.match(schema, /export type ChatDemoAiInbox =/);
  assert.match(schema, /_table: "chat_demo:messages"/);
  assert.match(schema, /_table: "chat_demo:direct_messages"/);
  assert.match(schema, /payload: ChatDemoAiInbox;/);
  assert.match(schema, /export type ChatDemoSendMessageResult = ChatDemoAiInbox \| null/);
});

function sliceBetween(source: string, start: string, end: string): string {
  const startIndex = source.indexOf(start);
  const endIndex = source.indexOf(end, startIndex + start.length);
  assert.ok(startIndex >= 0, `expected to find ${JSON.stringify(start)}`);
  assert.ok(endIndex > startIndex, `expected to find ${JSON.stringify(end)} after start marker`);
  return source.slice(startIndex, endIndex);
}

test('app joins through the procedure instead of inserting membership rows', async () => {
  const app = await readExample('src/App.tsx');
  assert.match(app, /api\.chatDemo\.joinRoom\(\{ room_id: ROOM \}\)/);
  assert.doesNotMatch(app, /db\.insert\(roomMembers\)/);
});

test('playwright helpers send room messages with CALL send_message', async () => {
  const spec = await readExample('tests/chat.spec.mjs');
  const insertUser = sliceBetween(spec, 'async function insertUserMessage', 'function sqlLiteral');

  assert.match(insertUser, /CALL chat_demo\.send_message/);
  assert.doesNotMatch(insertUser, /EXECUTE AS USER \$\{/);
});

test('schema.sql keeps teaching comments immediately before CREATE SHARED TABLE', async () => {
  const schemaSql = await readExample('kalam/schema.sql');
  assert.match(
    schemaSql,
    /-- Rooms everyone can list and create[^\n]*\nCREATE SHARED TABLE IF NOT EXISTS chat_demo\.rooms/,
  );
});
