use std::fmt::Write as _;

use kalamdb_sql::contracts::{ContractField, ContractSnapshot};

use super::{for_each_composite, live_fields};
use crate::workflow::schema::naming::AssignedNames;

pub fn render(snapshot: &ContractSnapshot, names: &AssignedNames) -> String {
    let mut out =
        String::from("// Generated by kalam schema gen. Do not edit.\nnamespace Kalam;\n\n");
    let mut root: Option<String> = None;
    for_each_composite(snapshot, names, |ident, fields| {
        let _ = writeln!(out, "table {ident} {{");
        for field in live_fields(fields) {
            let fbs_type = fbs_field_type(field, names);
            let _ = writeln!(out, "  {}: {};", field.name, fbs_type);
        }
        let _ = writeln!(out, "}}\n");
        if root.is_none() {
            root = Some(ident.to_string());
        }
    });
    if let Some(root) = root {
        let _ = writeln!(out, "root_type {root};");
    }
    out
}

fn fbs_field_type(field: &ContractField, names: &AssignedNames) -> String {
    let inner = if let Some(type_id) = &field.type_id {
        names.type_ident(type_id.as_str()).to_string()
    } else {
        match field
            .data_type
            .map(|dt| dt.sql_name())
            .unwrap_or_else(|| field.type_name.clone())
            .to_ascii_uppercase()
            .as_str()
        {
            "BOOLEAN" | "BOOL" => "bool".to_string(),
            "SMALLINT" | "INT2" | "INT" | "INTEGER" | "INT4" => "int".to_string(),
            "BIGINT" | "INT8" | "INT64" => "long".to_string(),
            "FLOAT" | "FLOAT4" | "REAL" => "float".to_string(),
            "DOUBLE" | "FLOAT8" => "double".to_string(),
            _ => "string".to_string(),
        }
    };
    if field.is_array {
        format!("[{inner}]")
    } else {
        inner
    }
}
