use std::fmt::Write as _;

use kalamdb_sql::contracts::{ContractField, ContractSnapshot};

use super::{for_each_composite, live_fields};
use crate::workflow::schema::naming::AssignedNames;

pub fn render(snapshot: &ContractSnapshot, names: &AssignedNames) -> String {
    let mut out = String::from(
        "# Generated by kalam schema gen. Do not edit.\nopenapi: 3.1.0\ninfo:\n  title: Kalam \
         named types\n  version: \"1\"\ncomponents:\n  schemas:\n",
    );
    for_each_composite(snapshot, names, |ident, fields| {
        let _ = writeln!(out, "    {ident}:");
        out.push_str("      type: object\n      properties:\n");
        for field in live_fields(fields) {
            let _ = writeln!(out, "        {}:", field.name);
            let _ = writeln!(out, "          {}", openapi_type(field, names));
        }
    });
    out
}

fn openapi_type(field: &ContractField, names: &AssignedNames) -> String {
    if let Some(type_id) = &field.type_id {
        let ident = names.type_ident(type_id.as_str());
        if field.is_array {
            format!(
                "type: array\n          items:\n            $ref: '#/components/schemas/{ident}'"
            )
        } else {
            format!("$ref: '#/components/schemas/{ident}'")
        }
    } else if field.is_array {
        "type: array\n          items:\n            type: string".to_string()
    } else {
        "type: string".to_string()
    }
}
