use std::fmt::Write as _;

use kalamdb_sql::contracts::{ContractField, ContractSnapshot};

use super::{for_each_composite, live_fields};
use crate::workflow::schema::naming::AssignedNames;

pub fn render(snapshot: &ContractSnapshot, names: &AssignedNames) -> String {
    let mut out = String::from(
        "// Generated by kalam schema gen. Do not edit.\nsyntax = \"proto3\";\npackage kalam;\n\n",
    );
    for_each_composite(snapshot, names, |ident, fields| {
        let _ = writeln!(out, "message {ident} {{");
        for field in live_fields(fields) {
            let number = if field.slot > 0 { field.slot } else { 1 };
            let ty = proto_type(field, names);
            let _ = writeln!(out, "  {ty} {} = {number};", field.name);
        }
        out.push_str("  reserved 1000 to 1999;\n}\n\n");
    });
    out
}

fn proto_type(field: &ContractField, names: &AssignedNames) -> String {
    let inner = if let Some(type_id) = &field.type_id {
        names.type_ident(type_id.as_str()).to_string()
    } else {
        "string".to_string()
    };
    if field.is_array {
        format!("repeated {inner}")
    } else {
        inner
    }
}
