import 'package:flutter_test/flutter_test.dart';

void main() {
  group('kalam CLI workflow Dart targets', () {
    const sampleKalamCliDart = '''
// Generated by kalam schema gen. Do not edit.

class Users {
  final int id;
  final String email;

  const Users({
    required this.id,
    required this.email,
  });
}
''';

    test('matches generated class contract', () {
      expect(sampleKalamCliDart, contains('Generated by kalam schema gen'));
      expect(sampleKalamCliDart, contains('class Users'));
      expect(sampleKalamCliDart, contains('final int id;'));
      expect(sampleKalamCliDart, contains('final String email;'));
    });
  });
}
